from pathlib import Path
import hashlib,json,shutil
ROOT=Path('/Users/okh/.codex/worktrees/review-regression/murderbird-uncaged');OUT=Path(__file__).parent;C=OUT/'coarse01';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def art(p):return {'path':str(p.relative_to(ROOT)),'bytes':p.stat().st_size,'sha256':sha(p)}
assert not(OUT/'manifest.json').exists()
BASE=ROOT/'assets/audit/whole-character-v32/attempt-form01/neck-screen';shutil.copy2(BASE/'screen.json',C/'executed-v32-baseline-screen.json');shutil.copy2(BASE/'executed-screen.py',C/'executed-v32-baseline-validator.py')
b=json.loads((BASE/'screen.json').read_text());n=json.loads((C/'neck-screen/screen.json').read_text());assert sha(BASE/'executed-screen.py')==sha(C/'neck-screen/executed-screen.py')
rows=[];observations=[]
for old,new in zip(b['poses'],n['poses']):
 assert old['pose']==new['pose'] and old['angles']==new['angles'];op={tuple(sorted((x['a'],x['b']))) for x in old['pairs']};np={tuple(sorted((x['a'],x['b']))) for x in new['pairs']};observations.extend(op)
 rows.append({'pose':new['pose'],'angles':new['angles'],'baselineCount':old['pairCount'],'candidateCount':new['pairCount'],'inherited':sorted(op&np),'introduced':sorted(np-op),'eliminated':sorted(op-np)})
comparison={'status':'Zero strict cross-owner surface-crossing pairs in the same seven tested poses','baselineNativeSHA256':b['nativeSHA256'],'candidateNativeSHA256':n['nativeSHA256'],'baselineScreenSHA256':sha(BASE/'screen.json'),'candidateScreenSHA256':sha(C/'neck-screen/screen.json'),'sameValidatorBytes':True,'validatorSHA256':sha(C/'neck-screen/executed-screen.py'),'method':n['method'],'comparisons':rows,'eliminatedPairObservations':len(observations),'eliminatedUniqueIdentities':len(set(observations)),'limits':['Strict finite edge/face crossing screen, not continuous collision or containment proof.','Same-owner overlaps are excluded by the unchanged validator.','No motion-limit, rest, head/eye/frame or runtime change.']}
assert not any(p['candidateCount'] for p in rows);(C/'comparison.json').write_text(json.dumps(comparison,indent=2)+'\n')
build=json.loads((C/'receipt.json').read_text());source=ROOT/'scripts/regions/whole-character-v33-neck-guards.py';native=ROOT/build['native']['path'];base=ROOT/build['base']['path'];assert sha(source)==build['sourceSHA256']==sha(C/'executed-region.py');assert sha(native)==n['nativeSHA256'];assert sha(base)==b['nativeSHA256']
records=build['result']['records'];maxmove=max(r.get('maximumInwardReceivingDisplacementM',0) for r in records);cheeks=[r for r in records if 'retainedVolumeFraction' in r]
reference=ROOT/'context/threads/assets/murderbird-owner-likeness-rejection-2026-09-28/2-Pasted-Image-2.jpg';camera={'position':[-6,-3.5,2.45],'target':[0,-.27,1.48],'orthoScale':1.3,'resolution':[900,900],'engine':'BLENDER_WORKBENCH','lighting':'paint.sl studio; neutral single color; no cast shadows'}
views=[{'pose':label,**art(C/'neck-screen'/f'{label}.png'),'camera':camera} for label in ['rest','maker-neck-jaw','contact-neck']]
receipt={'status':'Ready-to-compose bounded receiving-guard proposal; sampled screen zero, visual/owner/engineering acceptance separate','base':art(base),'native':art(native),'source':art(source),'executedSource':art(C/'executed-region.py'),'ownerWholeBirdReference':art(reference),'construction':'Thirty independently rigid directional guard grids re-formed inward behind their actual child finite-shell pitch envelope; two fixed root cheeks receive actual yaw/pitch shell envelope. No circumferential ring reconstruction, hidden plate, stretched part, new motion limit or powered Maker mechanism.','maximumInwardSurfaceDisplacementM':maxmove,'rootCheekVolumeRecords':cheeks,'finiteClosedPositiveNewSolids':len(records),'checks':build['checks'],'protectedContract':build['result']['structuralContract'],'changedMeshes':build['changedMeshes'],'strictComparison':art(C/'comparison.json'),'views':views,'limits':comparison['limits']+['Rays form a receiving proposal from29 relative child-pitch samples; finite sweep/radial containment between samples is not certified.','Existing frame attachments and all external-control/mechanism routes are unchanged; no new load-capacity/fastener claim.','Neutral construction study, not a finished material or owner likeness pass.','One candidate, no correction, no runtime/app edits or commits.']}
# Actual sample count is derived, avoiding a handwritten count assumption.
receipt['limits'][3]='Receiving proposal derived from '+str(len(build['result']['structuralContract']['relativeChildPitchSamplesRad']))+' actual relative child-pitch samples; clearance between them is not certified.'
(OUT/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n')
(OUT/'handoff.md').write_text('''# V33 neck receiving guards — one bounded candidate

The current curved directional rest surfaces govern this construction. Parent-course upper regions are re-formed inward behind the evaluated child-shell pitch sweep. The next course remains independently rigid and slides past the finite receiving return on its unchanged hinge. Full-width spherical/cylindrical rings are not introduced. Root cheeks receive the evaluated first-course yaw/pitch envelope.

Thirty proximal guards and two body-fixed receiving cheeks change; distal course4, ten root underlaps, head/eyes/frame/shafts, all rests, owners, materials and era tags are preserved. Every new solid is finite, closed and positive. Largest receiving displacement is10.94mm; cheeks retain98.09%/98.02% volume. Passive construction remains eligible in all three eras.

Exact unchanged seven-pose strict screen: baseline2/14/2/7/4/1/1 → candidate0/0/0/0/0/0/0. All eliminated identities and original witnesses remain explicit. The rest/Maker/contact images were inspected: throat curvature and layered directional protection remain present. Appearance remains a root/owner gate.

No continuous collision/containment, physical support, fastening, runtime-mechanism route or engineering pass is claimed. The unchanged validator excludes same-owner contacts. One candidate and no correction. apply() is composable on the exact V32 native; no root builder/app/runtime edit or commit.
''')
files=[{'path':p.relative_to(OUT).as_posix(),'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(OUT.rglob('*')) if p.is_file()];assert all(sha(OUT/r['path'])==r['sha256'] for r in files)
manifest={'schema':1,'status':receipt['status'],'base':receipt['base'],'native':receipt['native'],'externalSource':receipt['source'],'ownerWholeBirdReference':receipt['ownerWholeBirdReference'],'relativePathHashesChecked':True,'files':files};(OUT/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(json.dumps({'sourceSHA256':sha(source),'nativeSHA256':sha(native),'receiptSHA256':sha(OUT/'receipt.json'),'manifestSHA256':sha(OUT/'manifest.json'),'uniqueEliminatedIdentities':len(set(observations)),'poseEliminations':len(observations),'files':len(files),'outsideMeshes':build['checks']['outsideMeshesExact'],'maxDisplacementM':maxmove},indent=2))
