import json,hashlib,datetime
from pathlib import Path
R=Path('/Users/okh/.codex/worktrees/cg-architect-cycle01/murderbird-uncaged');D=R/'assets/audit/cg-supervised01/attempt09';ledger=json.loads((D/'claim-ledger.json').read_text());manifest=json.loads((D/'frozen-manifest.json').read_text());pins={x['path']:x for x in manifest['files']}
def evidence(path,usage,tier='live'):
 p=R/path;return {'path':path,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size,'use':usage,'evidence_status':tier}
common=[evidence('assets/audit/cg-supervised01/attempt09/review-contract.json','Frozen decision contract'),evidence('assets/audit/cg-supervised01/attempt09/frozen-manifest.json','All216 entries independently rehashed before and after'),evidence('assets/audit/cg-supervised01/attempt09/review-criteria.json','Criteria C00-C06'),evidence('goal.md','Pinned local shared mandate; no remote refresh in this review')]
whole=[evidence('assets/img/library/murderbird-locked-sept22-composite-owner-reissued-2026-10-03.jpg','Original controlling full-bird pixels inspected'),evidence('context/threads/assets/murderbird-camera-series-2026-09-05/murderbird-owner-preferred-july-reference.png','Original head-only pixels inspected; July body excluded'),evidence('assets/audit/cg-supervised01/attempt09/builder-source-before-candidate.jpg','Independent source/06/09 whole comparison'),evidence('assets/audit/cg-supervised01/attempt09/builder/head-neck.png','Candidate close-up inspected'),evidence('assets/audit/cg-supervised01/attempt09/maker-source-before-candidate.jpg','Era-source whole comparison'),evidence('assets/audit/cg-supervised01/attempt09/mechanic-source-before-candidate.jpg','Era-source whole comparison'),evidence('assets/audit/cg-supervised01/source-frames/first-choice-4s.png','Pinned video extracted frame actual pixels inspected; extraction not rerun'),evidence('assets/audit/cg-supervised01/attempt09/builder-neutral-eight-views.jpg','Integrated eight-angle pixels inspected')]
native=json.loads(Path('/tmp/cg-eq09-evidence-native-independent.json').read_text());glb=json.loads(Path('/tmp/cg-eq09-evidence-glb-independent.json').read_text());preservation=[];export=[]
for era in ['builder','maker','mechanic']:
 for attempt in ['attempt06','attempt09']:preservation.append(evidence(f'assets/models/cg-supervised01/{attempt}/murderbird-supervised-{era}.blend','Independent native readback compared original receiving payload/graphs/images'))
 preservation.append(evidence(f'assets/audit/cg-supervised01/attempt09/delivery-validation/cg-delivery09-native-{era}.json','Producer declared visibility and preservation receipt inspected; live independent readback corroborates'))
 export.append(evidence(f'assets/models/cg-supervised01/attempt09/murderbird-supervised-{era}.glb','Independent GLB binary/accessor/material/UV references/image decodability check'))
 export.append(evidence(f'assets/audit/cg-supervised01/attempt09/{era}/receipt.json','Native/export receipt; counts and UV/export implementation audited','analytical'))
browser=[evidence('assets/audit/cg-supervised01/attempt09/browser-review.json','Source-reported actual Chrome controls/load/fallback receipt; not independently rerun','historical'),evidence('assets/audit/cg-supervised01/attempt09/browser-three-era-contact.jpg','Actual saved browser screenshot pixels inspected; three-era and mode render evidence'),evidence('assets/audit/cg-supervised01/browser09-review.html','Actual local review source asset paths and limits inspected'),evidence('scripts/cg-supervised-browser05.js','Actual static local loader/lighting/control source inspected')]
claims=[]
findings={
 'CLM09-00':('disputed','C00 fails: whole images remain visibly short of controlling source character and owner acceptance is explicitly false/absent. Reject completion; no preservation/export PASS can satisfy this target. Source has a densely articulated riveted bronze/iron face/crown/neck, broader hooked bill with mapped plates, more compact body silhouette and substantial segmented feet.09 is visibly smoother, taller/upright and sparsely articulated, with a broad pale crown cap and large dark bill. Estimated source camera/depth limits measurement precision, not this qualitative discrepancy.',whole,'Correct the macro construction/surface match and obtain explicit owner artistic acceptance on the exact successor. No agent can grant that acceptance.'),
 'CLM09-01':('unknown','Actual before/after pixels show a warmer crown, a smaller recessed Advanced amber optic, changed breast courses and forward toes. Source-specific whole-character gain is mixed: pale smooth crown and regular/smooth breast/bill remain unlike the controlling source. Technical completion is supported separately; this evidence review does not establish the broad whole-character gain proposition.',whole,'Outcome reviewer should judge exact same-camera whole09 versus06 against canon; owner should decide whether these changes are useful.'),
 'CLM09-02':('supported','Independent six-file reopened native comparison corroborates all three receiving original payloads/maps/graphs/anchors:7424 mesh/empty objects,56 material graphs,160 packed FILE image byte+metadata records perera unchanged. Declared268 visibility changes perera match actual, including separately declared retired authoring ground. This is payload preservation, not unchanged rendered visibility.',preservation,'No additional preservation test required within the exact receiving06-to-final09 scope. Recheck any changed successor.'),
 'CLM09-03':('supported','All three actual static GLBs independently decode;642898 triangles,24 material batches each,46 embedded images Advanced/45 Maker/45 Mechanic; finite position/normal/UV attributes, unit normals, valid index/buffer bounds, texture UV channel references and decodable embedded images. Material triangle assignments equal receipts. Export code retains active render UV and explicit shader UVMap references. Saved actual Chrome evidence corroborates loading. Limit: native-to-GLB corner-by-corner equivalence and Chrome interactions were not independently rerun; shader/material data fidelity is supported by inspected code/receipts plus actual GLB data, not pixel parity.',export+browser,'Retain static-review/renderer-difference limits. A broad browser pixel-equivalence claim would need a dedicated comparison and is not supported.'),
 'CLM09-04':('supported','Actual three-era whole/native/browser pixels show dark Maker/Mechanic eyes and visible restrained Advanced amber. Actual GLB Maker/Mechanic protected core materials have no emissiveFactor/emissiveTexture; Advanced protected core uses emissiveFactor[1,1,1], emissive texture channel1 and emissiveStrength5. This supports the optic rule only; source-matched three-era surface finish distinction is still not established by these technical values.',whole+browser+export,'Owner/outcome review remains required for source-specific finish and awakened eye focal hierarchy.'),
 'CLM09-05':('unknown','Selected integrations exist in frozen09 and eight-angle pixels are readable, but regional custody/metrics do not establish retained whole-character usefulness or absence of a material integrated regression. Broad pale crown cap, simplified cheek/bill and bulky inherited talon bases remain visible. Packet declares billpeek/tip limitations openly. No held-out image or independent continuous-view occlusion/clearance test was run.',whole,'Adjudicate integrated whole silhouette and source fidelity; preserve declared tip/optic/grazing failures until a falsifiable check closes them.'),
 'CLM09-06':('supported','All216 frozen resource sizes/hashes match before and after; contact sources and all15 baseline-custody copied files hash-match actual source paths. All three before/candidate receipt camera/light/render fields match after excluding derived full_character_bounds (bounds are expected to change with exterior). Actual52 dist files match every build-record hash and exact path set; onlyV37 runtimeGLB is present, no supervised09/native/private/provenance payload is emitted. Build command execution remains source-reported, not independently rerun. Desktop browser receipt/screenshot custody is bound to frozen files. No remoteCI/deployment/main-sync claim is substantiated or requested.',common+browser+[evidence('assets/audit/cg-supervised01/build-verification-final09.json','Source-reported npm ci/build; all actualdist52 hashes and file set independently checked','historical'),evidence('assets/audit/cg-supervised01/attempt09/validation.json','69 native render technical delivery; expressly no likeness judgment','analytical')],'Preserve exact scope labels; rehash when files or build change. Remote publication/synchronization remains outside review.')}
for c in ledger['claims']:
 status,reason,ev,test=findings[c['claim_id']];claims.append({**c,'status':status,'finding':reason,'direct_evidence':ev,'next_test':test})
report={
 'role':'evidence','decision':'reject','artifact':'Frozen full09 three-era CG review study','question':json.loads((D/'review-contract.json').read_text())['question'],'reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'artifact_identity':common,'target_vs_study':{'completed_source_aligned_photoreal_target':'reject','admissible_review_study_delivery':'approve-with-limits','reason':'C00 target completion is materially unmet in actual source pixels and owner acceptance absent. Technical deliverables, custody and original receiving preservation support an editable static three-era review study with honest known limits; they cannot establish likeness.','approved_scope':'Review/owner comparison only. No production promotion, animation, engineering certification, remote synchronization, deployment or publication approval.'},
 'criteria_findings':[{'id':'C00','status':'disputed','reason':'Completed target and owner gate not satisfied.'},{'id':'C01','status':'unknown','reason':'Mixed incremental pixel changes; full-character source-specific gain not established by this evidence role.'},{'id':'C02','status':'disputed','reason':'Source construction gaps remain in crown/bill/cheek/connected breast and substantial feet.'},{'id':'C03','status':'disputed','reason':'Optic subclaim supported; the three candidate surface finishes remain visually similar and completed era-source finish distinction is not established.'},{'id':'C04','status':'supported','reason':'Independent original receiving all-era native readback PASS; declared visibility changes exact.'},{'id':'C05','status':'supported','reason':'Editable packed natives and static embedded GLB binary/material/UV channel delivery corroborated; no pixel equivalence/hierarchy/animation claim.'},{'id':'C06','status':'supported','reason':'Frozen evidence/custody and saved desktop browser proof present; live independent desktop interaction not rerun; mobile/performance/accessibility unknown.'}],
 'claims':claims,
 'checks_run':[{'check':'All manifest entries pre/post rehash','status':'PASS','count':216,'files':['/tmp/cg-eq09-evidence-manifest-before.json','/tmp/cg-eq09-evidence-manifest-after.json']},{'check':'Independent receiving06-to-final09 all-era native readback','status':'PASS','CPU_threads':2,'duration_seconds_approx':85,'scope':'No saves, render, or repository imports; independent custom digest covers payloads, all mesh attributes/UVs/groups/slots/transforms/modifiers/properties; graph RNA/defaults/links; packed FILE metadata+bytes','result':'/tmp/cg-eq09-evidence-native-independent.json','result_sha256':hashlib.sha256(Path('/tmp/cg-eq09-evidence-native-independent.json').read_bytes()).hexdigest(),'per_era':native['results']},{'check':'Independent all-era GLB binary decoder','status':'PASS','result':'/tmp/cg-eq09-evidence-glb-independent.json','result_sha256':hashlib.sha256(Path('/tmp/cg-eq09-evidence-glb-independent.json').read_bytes()).hexdigest(),'per_era':[{'era':x['era'],'sha256':x['sha256'],'triangles':x['triangles'],'materials':x['materials'],'embedded_images':len(x['images'])} for x in glb['results']]},{'check':'Baseline custody and camera/light/render matching','status':'PASS','file_count':15,'result':'/tmp/cg-eq09-evidence-custody-independent.json','note':'Only derived full_character_bounds differ; camera/light/render settings exactly equal on4 matched views perera.'},{'check':'Actualdist against build record','status':'PASS','file_count':52,'result':'/tmp/cg-eq09-evidence-dist-independent.json','note':'Exact recorded paths/hashes; onlyV37 runtimeGLB; no supervised/private/provenance material.'},{'check':'Original controlling source/scopedJuly/native whole/details/eightviews and saved browser pixels inspected','status':'live','paths':[x['path'] for x in whole]+['assets/audit/cg-supervised01/attempt09/browser-three-era-contact.jpg']}],
 'checks_not_run':['Independent actual Chrome pointer/era/light/fallback rerun (saved producer evidence and pixels inspected instead)','Independent complete native-to-GLB per-corner UV/material/texture transfer equality','Fresh native render (frozen69renderfiles rehashed)','npm ci/npm run build command rerun (actualdist all52 rehashed)','Video frame extraction rerun (originalvideo/frame hashes verified;4s actualpixel inspected)','Continuous all-camera occlusion/clearance, animation','Mobile/device/performance/accessibility suite','RemoteCI/deployment/main or external-system synchronization','Owner artistic acceptance'],
 'decisive_unresolved_claims':[{'claim_id':'CLM09-00','criterion':'C00','resolution':'Remain rejected as completed target until source construction/finish match and owner acceptance are present.'},{'claim_id':'CLM09-01','criterion':'C01','resolution':'Whole-character source-specific incremental gain must be judged from frozen actual pixels; cannot be inferred from custody/counts.'},{'claim_id':'CLM09-05','criterion':'C02','resolution':'Declared tip/optic/grazing and source construction limits remain open; local worker results not proof of integrated usefulness.'}],
 'independence':{'context':'Fresh evidence-role context; no other role outputs, prior Equilibrium opinions or architect process opinions read. Regional pins used for identity only. No children.','model':'Shared Sol model family per frozen contract; exact deployed reviewer model identifier unavailable to this evidence role','source_set':'Pinneddevelopment images/video, frozen09 native/export/render/browser/custody/build resources','retrieval':'Local read-only review2026-10-04T11:12-11:26Z','shared_model_limit':'Agreement from shared model family is correlated and not likeness proof.','shared_source_limit':'All pinned images/video seen during optimization; same development set and scaffold as producer. No protected/external holdout.','shared_method_limit':'Producer algorithms inspected; decisive native and GLB tests were independently authored under/tmp, but share Blender/glTF semantics and supplied receiving06 resources. Exact native-to-GLB corner equivalence not independently replayed.','evidence_status':'live local hash/data/pixel checks; analytical code/receipt review; historical savedChrome/build-command evidence; not-run remote/human/device checks'},
 'resources_unchanged':{'status':'PASS','all216_manifest_entries_post_review_match':True,'contract_sha256':'e2655b700d8cae824c8dafebcc1ca71a80b9d284cf7808d42a44d4172d6ac899','manifest_sha256':'378a01fb9430ade08c9de4c5bcc2026f9130bda95d8d57d237390bf12e748c36','mutations':'Only temporary independent scripts, logs and reports under/tmp; no saves to judged natives, no repository edits, commits, network publication or authority changes.'},
 'review_expiry_trigger':'Any change to frozen resource hashes, target claim, owner acceptance record or intended promotion/publication scope requires review.'}
Path('/tmp/cg-eq09-evidence.json').write_text(json.dumps(report,indent=2)+'\n');print('report written /tmp/cg-eq09-evidence.json',Path('/tmp/cg-eq09-evidence.json').stat().st_size)
