"""Write-once Advanced-only amber optic material proposal; all geometry/source records exact."""
from pathlib import Path
import bpy,json,hashlib,struct,copy,shutil,math
R=Path(__file__).resolve().parents[1];A=R/'assets/audit/whole-character-v38/optic-awake01';O=R/'assets/models/whole-character-v38/optic-awake01';SN=R/'assets/models/whole-character-v38/jaw-stock01/murderbird-v38-jaw-stock01.blend';SG=SN.with_name(SN.stem+'-rigid.glb');N=O/'murderbird-v38-optic-awake01.blend';G=N.with_name(N.stem+'-rigid.glb');NAME='V38 contrast / optic';PROPOSAL={'baseColorFactor':[.22,.065,.008,1.0],'metallicFactor':.2,'roughnessFactor':.28,'emissiveFactor':[.45,.13,.015]}
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
assert sha(SN)=='507a58f5670677276f8f06d3769deb9eb6cbd178a20f20a2993986d02374f63a';assert sha(SG)=='0099e5026750db916bb05ac1c66f3fc51a169d941448d6b834d6058e33d0dc04';assert not N.exists()and not G.exists();O.mkdir(parents=True,exist_ok=True);A.mkdir(parents=True,exist_ok=True);shutil.copy2(__file__,A/'executed-builder.py')
def glb(p):
 raw=p.read_bytes();chunks=[];i=12
 while i<len(raw):n,k=struct.unpack_from('<II',raw,i);i+=8;chunks.append((k,raw[i:i+n]));i+=n
 return chunks,json.loads(chunks[0][1])
def node_sig():
 return {o.name:hashlib.sha256(json.dumps({'parent':o.parent.name if o.parent else None,'local':[list(row)for row in o.matrix_local],'extras':dict(o.items()),'vertices':[list(v.co)for v in o.data.vertices]if o.type=='MESH'else None,'faces':[list(f.vertices)for f in o.data.polygons]if o.type=='MESH'else None,'materialSlots':[m.name if m else None for m in o.data.materials]if o.type=='MESH'else None},sort_keys=True,default=lambda x:list(x)).encode()).hexdigest()for o in bpy.data.objects}
def material_sig(m):
 return json.dumps({'extras':dict(m.items()),'diffuse':list(m.diffuse_color),'metallic':m.metallic,'roughness':m.roughness,'nodes':[(n.name,n.type,[(i.name,list(i.default_value)if hasattr(i.default_value,'__len__')else i.default_value)for i in n.inputs if hasattr(i,'default_value')])for n in m.node_tree.nodes]if m.node_tree else None},sort_keys=True,default=lambda x:list(x))
bpy.ops.wm.open_mainfile(filepath=str(SN));bpy.context.view_layer.update();nodesBefore=node_sig();materialsBefore={m.name:material_sig(m)for m in bpy.data.materials};m=bpy.data.materials[NAME];bsdf=next(n for n in m.node_tree.nodes if n.type=='BSDF_PRINCIPLED');assert not any(i.is_linked for i in bsdf.inputs if i.name in ['Base Color','Roughness','Emission Color','Emission Strength']);assert abs(bsdf.inputs['Emission Strength'].default_value-1)<1e-6
profiles=json.loads(m['eraFinishes']);oldProfiles=copy.deepcopy(profiles);assert set(profiles)=={'builder'};profiles['builder']=copy.deepcopy(PROPOSAL);m['eraFinishes']=json.dumps(profiles,separators=(',',':'));m.diffuse_color=PROPOSAL['baseColorFactor'];m.roughness=PROPOSAL['roughnessFactor'];bsdf.inputs['Base Color'].default_value=PROPOSAL['baseColorFactor'];bsdf.inputs['Roughness'].default_value=PROPOSAL['roughnessFactor'];bsdf.inputs['Emission Color'].default_value=PROPOSAL['emissiveFactor']+[1.0]
assert nodesBefore==node_sig();materialChanged=[n for n in materialsBefore if materialsBefore[n]!=material_sig(bpy.data.materials[n])];assert materialChanged==[NAME];bpy.context.preferences.filepaths.save_version=0;bpy.ops.wm.save_as_mainfile(filepath=str(N),check_existing=False);bpy.ops.wm.open_mainfile(filepath=str(N));assert nodesBefore==node_sig()
# Verify actual Blender exporter sees the amended native Principled fields.
_,source=glb(SG);assert source['materials'][5]['name']==NAME;users=[]
for n in source['nodes']:
 if 'mesh'in n and any(p.get('material')==5 for p in source['meshes'][n['mesh']]['primitives']):users.append(n['name'])
assert sorted(users)==['V31 Advanced optical aperture -1','V31 Advanced optical aperture 1'];bpy.ops.object.select_all(action='DESELECT')
for name in users:o=bpy.data.objects[name];o.hide_set(False);o.hide_viewport=False;o.select_set(True)
CHECK=A/'native-optic-export-check.glb';bpy.ops.export_scene.gltf(filepath=str(CHECK),export_format='GLB',use_selection=True,export_yup=True,export_apply=False,export_extras=True,export_cameras=False,export_lights=False,export_animations=False,export_materials='EXPORT');_,check=glb(CHECK);exported=next(m for m in check['materials']if m['name']==NAME)
actual={'baseColorFactor':exported['pbrMetallicRoughness']['baseColorFactor'],'metallicFactor':exported['pbrMetallicRoughness']['metallicFactor'],'roughnessFactor':exported['pbrMetallicRoughness']['roughnessFactor'],'emissiveFactor':exported['emissiveFactor']}
for k,v in PROPOSAL.items():
 if isinstance(v,list):assert all(abs(x-y)<1e-6 for x,y in zip(actual[k],v)),(k,actual[k],v)
 else:assert abs(actual[k]-v)<1e-6
assert json.loads(bpy.data.materials[NAME]['eraFinishes'])==profiles
# Preserve complete source GLB geometry/node/othermaterial records and binary chunks.
chunks,doc=glb(SG);target=doc['materials'][5];before=copy.deepcopy(target);target['pbrMetallicRoughness']['baseColorFactor']=PROPOSAL['baseColorFactor'];target['pbrMetallicRoughness']['roughnessFactor']=PROPOSAL['roughnessFactor'];target['emissiveFactor']=PROPOSAL['emissiveFactor'];target['extras']['eraFinishes']['builder']=copy.deepcopy(PROPOSAL);assert all(doc['materials'][i]==source['materials'][i]for i in range(12)if i!=5);assert {k:v for k,v in doc.items()if k!='materials'}=={k:v for k,v in source.items()if k!='materials'}
j=json.dumps(doc,separators=(',',':')).encode();j+=b' '*((-len(j))%4);raw=bytearray(struct.pack('<4sII',b'glTF',2,0))
for k,c in chunks:d=j if k==0x4e4f534a else c;raw+=struct.pack('<II',len(d),k)+d
struct.pack_into('<I',raw,8,len(raw));G.write_bytes(raw);finalChunks,finalDoc=glb(G);assert [(k,c)for k,c in chunks if k!=0x4e4f534a]==[(k,c)for k,c in finalChunks if k!=0x4e4f534a]
scope={'changed':[],'added':{},'removed':[],'changedNodes':[],'allowedTranslation':[],'allowedReparent':{},'allowedExtras':{},'changedMaterials':[NAME],'allowedMaterialFields':{NAME:['pbrMetallicRoughness.baseColorFactor','pbrMetallicRoughness.roughnessFactor','emissiveFactor','extras.eraFinishes.builder']},'baselineNativeSHA256':sha(SN),'baselineGLBSHA256':sha(SG),'candidateNativeSHA256':sha(N),'candidateGLBSHA256':sha(G)};(A/'scope.json').write_text(json.dumps(scope,indent=2)+'\n')
receipt={'status':'One moderate Advanced amber optic proposal; rootactualbrowser/owneracceptance pending','native':str(N.relative_to(R)),'nativeSHA256':sha(N),'glb':str(G.relative_to(R)),'glbSHA256':sha(G),'sourceNativeSHA256':sha(SN),'sourceGLBSHA256':sha(SG),'changedMaterial':NAME,'materialIndex':5,'affectedNodes':users,'sourceMaterial':before,'candidateMaterial':target,'nativeExporterFactors':actual,'nativeExporterCheckSHA256':sha(CHECK),'nativeMirrorFields':'Principled BaseColor/Roughness/EmissionColor withEmissionStrength1 retained; diffusecolor/roughness mirrors updated; JSONeraFinishes.builder exactly amended','nativeUnchangedNodeGeometryTransformExtraRecords':len(nodesBefore),'otherNativeMaterialsChanged':[],'other11GLBMaterialsExact':True,'allGLBNodesMeshesAccessorsBuffersAndOtherRecordsExact':True,'allBinaryChunksByteExact':True,'builderOnlyEligibilityExact':True,'earlierEraProfilesAbsentAsSource':True,'recipeSHA256':sha(A/'executed-builder.py'),'limits':['Moderate emission/no bloom/laser/chestlight or otherera expansion.','Nativeexportfloat correspondence tolerance1e-6; finalsourceGLB materialrecord uses exactproposal literals.','No clayrenders; actualBrowsercalibration rootowned.','Materialcalibration is not ownerlikeness or wholebodyacceptance.']};(A/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n');print('READY',N,sha(N),G,sha(G),flush=True)
