from pathlib import Path
import json,hashlib,subprocess
R=Path('/Users/okh/.codex/worktrees/review-regression/murderbird-uncaged');A=R/'assets/audit/whole-character-v34/attempt-form01/leg-composition-screen';M=A.parent/'motion'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def art(p):return {'path':str(p.relative_to(R)),'bytes':p.stat().st_size,'sha256':sha(p)}
N=R/'assets/models/whole-character-v34/attempt-form01/murderbird-whole-character-v34.blend';G=N.with_suffix('.glb')
assert sha(N)=='3f4c12983feea5e4d45f5609d749c1dfa78ecdafc34936d3e702ffa403fed716';assert sha(G)=='32a53dd3c26209fda81a2a6cfbc6a16080910bdf1ec73ed6b6000fec1251c41d' and G.stat().st_size==13169324
f=json.loads((A/'focused-joint-screen.json').read_text());p=json.loads((A/'pose-matrices.json').read_text());support=json.loads((A/'preservation-support-proof.json').read_text());motion=json.loads((M/'motion-validation.json').read_text())
assert f['sourceGLBSHA256']==p['sourceGLBSHA256']==sha(G)==motion['model']['sha256'];assert f['nativeSHA256']==sha(N)
assert len(f['poses'])==10 and all(not r['introduced'] for r in f['poses'])
assert support['regionToCompositionChecks']['accepted144MeshSignaturesExact']==144 and support['regionToCompositionChecks']['namedRestOwnersExact']==54
assert len(support['evaluatedFiniteClosedChangedSolids'])==144 and len(support['protectedGroundSupportGeometrySamples'])==10 and all(r['protectedFootToeDigitMeshCount']==60 and r['maximumBoundsDeltaM']==0 for r in support['protectedGroundSupportGeometrySamples'])
for source,h in p['sourceHashes'].items():assert sha(R/source)==h,source
for source in motion['executedSources']:assert sha(Path(source['path']))==source['sha256'],source['path']
assert sha(R/'scripts/regions/whole-character-v34-leg-mass.py')==sha(A/'executed-whole-character-v34-leg-mass.py')=='30a9f370083288bcded21bfb8563e1124ded9f90e470fc022401c9a0c7948b87'
retained={};rows=[]
for row in f['poses']:
 rows.append({'pose':row['pose'],'baseline':row['baseline']['pairCount'],'candidate':row['candidate']['pairCount'],'introduced':len(row['introduced']),'retained':len(row['retained']),'resolved':len(row['resolved'])})
 for pair in row['retained']:
  key=tuple(sorted([pair['a'],pair['b']]));retained.setdefault(key,{'parts':list(key),'owners':pair['owners'],'poses':[]})['poses'].append(row['pose'])
head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip();command='node scripts/validate-whole-character-v25-motion.mjs --model '+str(G.relative_to(R))+' --output '+str(M.relative_to(R))
receipt={'status':'Exact final V34 Form01 composition: zero introduced leg-neighbor identities in10 fresh GLB/controller samples;32 inherited strict identities unresolved. No full-fit or likeness acceptance.','head':head,'native':art(N),'glb':art(G),'baseSHA256':f['baselineSHA256'],'legModule':art(R/'scripts/regions/whole-character-v34-leg-mass.py'),'actualPoseCapture':art(A/'executed-capture-final-poses.mjs'),'actualPoseTable':art(A/'pose-matrices.json'),'actualStrictScreen':art(A/'focused-joint-screen.json'),'evaluatedGeometryAndProtectedSupportProof':art(A/'preservation-support-proof.json'),'sourceHashes':p['sourceHashes'],'checks':support['regionToCompositionChecks'],'scope':{'builderVisibleAdjacentMeshes':f['poses'][0]['candidate']['allVisibleMeshes'],'screenedLegFootBodyReceiverMeshes':f['poses'][0]['candidate']['screenedLegMeshes'],'poseCount':10,'freshPoseSourceSHA256':sha(G),'rawAndEvaluatedFiniteClosedPositiveChangedMeshCount':144,'protectedFootToeDigitMeshes':60,'maximumProtectedContactBoundsDeltaM':0,'allNamedRestOwnersExact':54},'poseCounts':rows,'uniqueIntroducedIdentities':0,'uniqueInheritedIdentities':len(retained),'remainingPairs':list(retained.values()),'cameras':art(A/'camera-contract.json'),'actualViews':[art(v) for v in sorted(A.glob('*.png'))],'motion':{'command':command,'report':art(M/'motion-validation.json'),'summary':motion['summary'],'loaded':motion['loaded'],'scenarioCount':len(motion['checks']),'totalFrames':sum(c['metrics']['frames'] for c in motion['checks']),'totalGeometrySamples':sum(c['metrics']['samples'] for c in motion['checks']),'maximumFootSolveErrorM':max(c['metrics']['maxFootSolveErrorM'] for c in motion['checks']),'maximumSupportActualDriftM':max(c['metrics']['maxSupportActualDriftM'] for c in motion['checks']),'maximumPlantedFloorOffsetM':max(c['metrics']['maxPlantedFloorOffsetM'] for c in motion['checks']),'maximumResetLocalMatrixDelta':max(c['reset']['maxLocalMatrixDelta'] for c in motion['checks'])},'limitations':['Every remaining identity remains strict and cross-owner; inheritance is a provenance distinction, not clearance approval.','24 metatarsal-rail↔toe/digit bearing/link pairs,4 repeated thigh cheek↔shin primary/.28 collar pairs, and4 Makerpeak additional thigh/shin pairs remain unresolved.','Authored rest plus9 actual fresh export/controller samples; unchanged strict kernel, no pair exemptions, no continuous collision or physics proof.','Full-motion harness reports actual ordinary kinematics/contact/rigid attachment math and source visibility. Procedural tail and era machinery are NOT TESTED by that harness.','All144 regional edited mesh signatures and54 named rest nodes are exact on finalnative; all60 protected evaluated contact bounds/minZ are equal to V33 under each finalGLBpose.','No geometry, runtime, movement limits, source models, app, docs, or committed state altered by this diagnostic. WebGL and owner art acceptance remain separate.'],'noCommitOrPublication':True}
(A/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n')
(M/'receipt.json').write_text(json.dumps({'status':motion['status'],'head':head,'command':command,'native':art(N),'glb':art(G),'modelUnchanged':True,'report':art(M/'motion-validation.json'),'log':art(M/'motion-validation.log'),'loaded':motion['loaded'],'summary':motion['summary'],'scenarioCount':len(motion['checks']),'totalFrames':receipt['motion']['totalFrames'],'totalGeometrySamples':receipt['motion']['totalGeometrySamples'],'metrics':{k:v for k,v in receipt['motion'].items() if k.startswith('maximum')},'limits':motion['limits'],'sourceHashes':motion['executedSources'],'noPhysicsFullEraFitOrArtAcceptance':True},indent=2)+'\n')
for folder in [A,M]:
 files=[p for p in folder.rglob('*') if p.is_file() and p.name!='manifest.json'];manifest={'status':'Exact composition diagnostic frozen; source/model unchanged','head':head,'nativeSHA256':sha(N),'glbSHA256':sha(G),'artifacts':[art(p) for p in sorted(files)]};out=folder/'manifest.json';assert not out.exists();out.write_text(json.dumps(manifest,indent=2)+'\n')
 assert all(sha(R/r['path'])==r['sha256'] and (R/r['path']).stat().st_size==r['bytes'] for r in manifest['artifacts'])
 print(json.dumps({'receipt':art(folder/'receipt.json'),'manifest':art(out),'artifactCount':len(files)}))
