from pathlib import Path
import bpy,bmesh,hashlib,json,math
from mathutils import Vector,Quaternion
OUT=Path('/tmp/v31-head-reconstruction/attempt05-fit-f');NATIVE=OUT/'head-reconstruction.blend';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();h=sha(NATIVE);bpy.ops.wm.open_mainfile(filepath=str(NATIVE));bpy.context.view_layer.update();p=(OUT/'screen/executed-pose-input.py').read_text();exec(p[p.index('CHAIN='):p.index('def inside')]);receipt=json.loads((OUT/'receipt.json').read_text());r={'nativeSHA256':h,'moduleSHA256':receipt['sourceSHA256'],'rendererSHA256':sha(Path(__file__)),'poseInputSHA256':sha(OUT/'screen/executed-pose-input.py'),'views':[]}
o=bpy.data.objects['V23 cervical 4 directional guard 10'];ev=o.evaluated_get(bpy.context.evaluated_depsgraph_get());m=ev.to_mesh();m.calc_loop_triangles();bm=bmesh.new();bm.from_mesh(m);r['matingGuardFinite']={'object':o.name,'owner':o.parent.name,'nonFinite':sum(not math.isfinite(c) for v in m.vertices for c in v.co),'nonManifoldEdges':sum(not e.is_manifold for e in bm.edges),'degenerateTriangles':sum((m.vertices[t.vertices[1]].co-m.vertices[t.vertices[0]].co).cross(m.vertices[t.vertices[2]].co-m.vertices[t.vertices[0]].co).length<1e-12 for t in m.loop_triangles),'positiveVolumeM3':bm.calc_volume(signed=True),'modifiers':[(x.name,x.type) for x in o.modifiers]};bm.free();ev.to_mesh_clear();scene=bpy.context.scene
for o in bpy.data.objects:
 if o.type=='MESH':o.hide_render='builder' not in o.get('exteriorEras','maker,mechanic,builder').split(',')
 elif o.type=='CURVE':o.hide_render=True
scene.render.engine='BLENDER_WORKBENCH';s=scene.display.shading;s.light='STUDIO';s.studio_light='paint.sl';s.color_type='SINGLE';s.single_color=(.56,.58,.60);s.show_shadows=False;s.show_cavity=True;s.cavity_type='BOTH';s.background_type='WORLD';scene.world.color=(.12,.13,.14);scene.render.resolution_x=scene.render.resolution_y=900;scene.render.resolution_percentage=100;scene.render.image_settings.file_format='PNG';d=bpy.data.cameras.new('Final fit pose review');d.type='ORTHO';d.ortho_scale=.95;cam=bpy.data.objects.new(d.name,d);scene.collection.objects.link(cam);scene.camera=cam;focus=Vector(receipt['views'][1]['camera']['target']);cam.location=receipt['views'][1]['camera']['position'];cam.rotation_euler=(focus-cam.location).to_track_quat('-Z','Y').to_euler()
for state in (STATES[1],STATES[3]):
 pose(state);scene.render.filepath=str(OUT/('native-'+state[0]+'.png'));bpy.ops.render.render(write_still=True);r['views'].append({'pose':state,'sha256':sha(Path(scene.render.filepath)),'camera':receipt['views'][1]['camera']})
assert sha(NATIVE)==h;(OUT/'pose-render-receipt.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(r['matingGuardFinite']))
