from pathlib import Path
import bpy,json,hashlib,math
R=Path('/Users/okh/.codex/worktrees/review-regression/murderbird-uncaged');A=Path(__file__).parent;S=R/'assets/audit/whole-character-v35/regional-studies/torso-integration/attempt05';rec=json.loads((S/'receipt.json').read_text());comp=json.loads((A.parent/'receipt.json').read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();h=lambda d:hashlib.sha256(json.dumps(d,separators=(',',':'),sort_keys=True).encode()).hexdigest();names=sorted(rec['result']['changedMeshes']+rec['result']['added']);assert len(names)==65
paths=[R/rec['native']['path'],R/comp['native']['path']];hashes=[rec['native']['sha256'],comp['native']['sha256']]
def snap(path):
 bpy.ops.wm.open_mainfile(filepath=str(path));bpy.context.view_layer.update();dg=bpy.context.evaluated_depsgraph_get();out={}
 for name in names:
  o=bpy.data.objects[name];ev=o.evaluated_get(dg);m=ev.to_mesh();m.calc_loop_triangles();v=[list(ev.matrix_world@p.co) for p in m.vertices];assert all(math.isfinite(c) for p in v for c in p)
  evaluated={'worldVertices':v,'triangles':[list(t.vertices) for t in m.loop_triangles]};ev.to_mesh_clear()
  raw={'vertices':[list(p.co) for p in o.data.vertices],'edges':[list(e.vertices) for e in o.data.edges],'faces':[list(p.vertices) for p in o.data.polygons],'materialIndex':[p.material_index for p in o.data.polygons],'smooth':[p.use_smooth for p in o.data.polygons]}
  out[name]={'parent':o.parent.name,'matrixWorld':[list(row) for row in o.matrix_world],'matrixLocal':[list(row) for row in o.matrix_local],'materials':[m.name if m else None for m in o.data.materials],'eras':o.get('exteriorEras'),'role':o.get('surfaceRole'),'rawSHA256':h(raw),'rawComponentSHA256':{k:h(v) for k,v in raw.items()},'rawCanonicalEdgesSHA256':h(sorted(sorted(e) for e in raw['edges'])),'evaluatedWorldSHA256':h(evaluated),'evaluatedVertices':len(v),'evaluatedTriangles':len(evaluated['triangles']),'finite':True}
 for removed in rec['result']['removed']:assert removed not in bpy.data.objects
 return out
assert all(sha(p)==s for p,s in zip(paths,hashes));a=snap(paths[0]);b=snap(paths[1]);rows=[{'name':n,'exact':a[n]==b[n],'regional':a[n],'composed':b[n]} for n in names];result={'status':'Exact 65-mesh evaluated-world torso composition parity; transfers bounded regional witnesses only, not fresh whole-body physics or artistic acceptance','regionalNative':rec['native'],'composedNative':comp['native'],'executedSourceSHA256':sha(Path(__file__)),'regionalModuleSHA256':rec['sourceSHA256'],'all65Exact':all(r['exact'] for r in rows),'all65EvaluatedWorldGeometryExact':all(r['regional']['evaluatedWorldSHA256']==r['composed']['evaluatedWorldSHA256'] for r in rows),'all65ParentsRestsMaterialsEraExact':all(all(r['regional'][k]==r['composed'][k] for k in ['parent','matrixWorld','matrixLocal','materials','eras','role']) for r in rows),'rawOrderDifferences':[{'name':r['name'],'differingComponents':[k for k,v in r['regional']['rawComponentSHA256'].items() if v!=r['composed']['rawComponentSHA256'][k]],'canonicalEdgesExact':r['regional']['rawCanonicalEdgesSHA256']==r['composed']['rawCanonicalEdgesSHA256']} for r in rows if r['regional']['rawSHA256']!=r['composed']['rawSHA256']],'all4RemovedAbsent':True,'comparison':'Raw mesh data, evaluated world vertices and triangulation, local/world rest matrices, parent, materials, era and role; root jaw/socket metadata outside torso ignored','meshes':rows,'regionalScreens':{'opening':{'path':str((S/'screen.json').relative_to(R)),'sha256':sha(S/'screen.json')},'neck':{'path':str((S/'neck-screen/screen.json').relative_to(R)),'sha256':sha(S/'neck-screen/screen.json')},'fixedJunctions':{'path':str((S/'fixed-junction-disposition.json').relative_to(R)),'sha256':sha(S/'fixed-junction-disposition.json')}},'nativeHashesUnchanged':all(sha(p)==s for p,s in zip(paths,hashes))};(A/'composition-parity.json').write_text(json.dumps(result,indent=2)+'\n');assert result['all65EvaluatedWorldGeometryExact'] and result['all65ParentsRestsMaterialsEraExact'];assert all(d['differingComponents']==['edges'] and d['canonicalEdgesExact'] for d in result['rawOrderDifferences']);assert result['nativeHashesUnchanged'];print('ALL65WORLD_GEOMETRY_PARENTS_RESTS_MATERIALS_ERAS_EXACT',len(result['rawOrderDifferences']),'raw edge-order-only differences',hashes)
