from pathlib import Path
import bpy,bmesh,runpy,json,hashlib,shutil,math
from mathutils import Vector
ROOT=Path('/Users/okh/.codex/worktrees/review-regression/murderbird-uncaged');OUT=Path('/tmp/v27-cranial-wrap/attempt03');OUT.mkdir(exist_ok=False);BASE=ROOT/'assets/models/whole-character-v26/attempt-form01/murderbird-whole-character-v26.blend';SRC=ROOT/'scripts/regions/whole-character-v27-cranial-wrap.py';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();assert sha(BASE)=='f897b3310af0c9d8b5e079484bcd9b8863e35c12e6b2be26601ad56700b65564';bpy.ops.wm.open_mainfile(filepath=str(BASE));bpy.context.view_layer.update();h=runpy.run_path(str(ROOT/'scripts/build-uncaged-alignment-v7.py'));mats={m.name:h['material_signature'](m) for m in bpy.data.materials};shutil.copyfile(SRC,OUT/'executed-cranial-wrap.py');shutil.copyfile(__file__,OUT/'executed-study.py');module=runpy.run_path(str(OUT/'executed-cranial-wrap.py'));result=module['apply']();after=h['scene_snapshot']();assert mats=={m.name:h['material_signature'](m) for m in bpy.data.materials}
solids=[];dg=bpy.context.evaluated_depsgraph_get();points=[]
for n in result['changedMeshes']+result['added']:
 o=bpy.data.objects[n];ev=o.evaluated_get(dg);m=ev.to_mesh();v=[ev.matrix_world@v.co for v in m.vertices];assert all(math.isfinite(c) for p in v for c in p);points+=v;bm=bmesh.new();bm.from_mesh(m);closed=all(e.is_manifold for e in bm.edges);volume=bm.calc_volume(signed=True);bm.free();cp=m.copy();repair=cp.validate(verbose=False);bpy.data.meshes.remove(cp);solids.append({'name':n,'closed':closed,'signedVolume':volume,'validateRepair':repair,'evaluatedBounds':[[min(p[k] for p in v) for k in range(3)],[max(p[k] for p in v) for k in range(3)]]});ev.to_mesh_clear()
assert all(s['closed'] and s['signedVolume']>0 and not s['validateRepair'] for s in solids),[s for s in solids if not s['closed'] or s['signedVolume']<=0 or s['validateRepair']]
assert all(-.32<p.x<.32 and -.85<p.y<.05 and 1.35<p.z<2.10 for p in points)
bpy.context.preferences.filepaths.save_version=0;native=OUT/'cranial-wrap.blend';bpy.ops.wm.save_as_mainfile(filepath=str(native),check_existing=False);bpy.ops.wm.open_mainfile(filepath=str(native));assert h['scene_snapshot']()==after;assert sha(BASE)=='f897b3310af0c9d8b5e079484bcd9b8863e35c12e6b2be26601ad56700b65564'
r={'baseSHA256':sha(BASE),'sourceSHA256':sha(SRC),'nativeSHA256':sha(native),'rendererSHA256':sha(Path(__file__)),'result':result,'finiteSolids':solids,'materialsExact':True,'saveReopenExact':True,'views':[]};(OUT/'receipt.json').write_text(json.dumps(r,indent=2)+'\n')

print(json.dumps({'sourceSHA256':r['sourceSHA256'],'nativeSHA256':r['nativeSHA256'],'solids':len(solids),'changed':len(result['changedMeshes']),'added':len(result['added']),'removed':len(result['removed'])}))
