from pathlib import Path
import json,hashlib,shutil
ROOT=Path('/Users/okh/.codex/worktrees/review-regression/murderbird-uncaged');AUDIT=ROOT/'assets/audit/whole-character-v30/attempt-form02';NECK=AUDIT/'neck-screen';HEAD=AUDIT/'head-screen';OLD=ROOT/'assets/audit/whole-character-v29/attempt-fit01/neck-screen';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
shutil.copyfile('/tmp/v30-final-neck-screen.log',NECK/'screen.log');shutil.copyfile(OLD/'screen.json',NECK/'executed-v29-baseline-input.json');shutil.copyfile(OLD/'executed-screen.py',NECK/'executed-v29-baseline-screen-input.py');shutil.copyfile('/tmp/v30-final-screen-commands.json',NECK/'executed-check-arguments.json');shutil.copyfile(__file__,NECK/'executed-comparison-preservation.py')
a=json.loads((NECK/'executed-v29-baseline-input.json').read_text());b=json.loads((NECK/'screen.json').read_text());assert a['nativeSHA256']=='04040543c39e98dd3d20da3d51a5ba40fd87151315ef074d328276eed97c63e7';assert b['nativeSHA256']=='207e32fe640fcc5cc9d3bef7bea4e07d302ec5bc06cc6642075df144d295e275';rows=[]
for old,new in zip(a['poses'],b['poses']):
 assert old['pose']==new['pose'] and old['angles']==new['angles'];pairs=lambda p:{tuple(sorted([v['a'],v['b']])) for v in p['pairs']};before=pairs(old);after=pairs(new)
 rows.append({'pose':new['pose'],'angles':new['angles'],'baselinePairCount':old['pairCount'],'finalPairCount':new['pairCount'],'introduced':[list(x) for x in sorted(after-before)],'eliminated':[list(x) for x in sorted(before-after)],'inherited':[list(x) for x in sorted(before&after)]})
comp={'nativeSHA256':b['nativeSHA256'],'baselineNativeSHA256':a['nativeSHA256'],'baselineReceiptSHA256':sha(NECK/'executed-v29-baseline-input.json'),'finalReceiptSHA256':sha(NECK/'screen.json'),'finalScreenSourceSHA256':sha(NECK/'executed-screen.py'),'frozenBaselineSourceSHA256':sha(NECK/'executed-v29-baseline-screen-input.py'),'status':'FAIL: actual final cervical guard/receiving contacts remain at all seven sampled poses. Counts are identities, not depth or severity.','methodLimits':b['method'],'poses':rows}
(NECK/'comparison.json').write_text(json.dumps(comp,indent=2)+'\n')
head=json.loads((HEAD/'scoped-screen.json').read_text());h={'nativeSHA256':head['nativeSHA256'],'baselineNativeSHA256':head['baseSHA256'],'headSourceSHA256':head['sourceSHA256'],'jawCounts':[p['strictPairCount'] for p in head['poses']['candidate'] if p['pose']=='jaw'],'capCounts':[p['strictPairCount'] for p in head['poses']['candidate'] if p['pose']=='cap'],'inheritedJournalIdentities':[['Forked forged mandible -1','Coaxial mandible journal'],['Forked forged mandible 1','Coaxial mandible journal.001']],'newPairIdentities':sorted({tuple(x) for p in head['comparisons'] for x in p['introduced']}),'eraMetadataExact':head['eraPropsExactAllChanged'],'status':'No introduced head jaw/cap strict pair in sampled final native poses; inherited journal contacts remain. Not whole-character or continuous clearance.','methodLimits':head['method']};(HEAD/'handoff.json').write_text(json.dumps(h,indent=2)+'\n')
for out in (HEAD,NECK):
 files=[{'path':str(p.relative_to(out)),'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(out.rglob('*')) if p.is_file()];man={'nativeSHA256':b['nativeSHA256'],'files':files,'modelsModified':False,'binariesDuplicated':False};(out/'manifest.json').write_text(json.dumps(man,indent=2)+'\n');assert all(sha(out/f['path'])==f['sha256'] and (out/f['path']).stat().st_size==f['bytes'] for f in files);print(json.dumps({'folder':str(out),'manifestSHA256':sha(out/'manifest.json'),'filesValidated':len(files)}))
print(json.dumps({'neckComparisons':rows}))
