from pathlib import Path
import shutil,json,hashlib
ROOT=Path('/Users/okh/.codex/worktrees/review-regression/murderbird-uncaged');SRC=Path('/tmp/v30-head-form');OUT=ROOT/'assets/audit/whole-character-v30/regional-studies/head-form';OUT.mkdir(parents=True,exist_ok=False);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
for label in ('attempt01','attempt02','attempt03'):
 shutil.copytree(SRC/label,OUT/label)
for n in ('inventory.py','inventory.json','inventory.log','write-source.py','correct02.py','correct03.py','study01.py','study02.py','study03.py','study01.log','study02.log','study03.log','render-before.py','render-before.log','scoped-screen.py'):
 if (SRC/n).is_file():shutil.copyfile(SRC/n,OUT/n)
shutil.copyfile(__file__,OUT/'executed-preservation.py')
final=json.loads((OUT/'attempt03/receipt.json').read_text());screen=json.loads((OUT/'attempt03/scoped-screen.json').read_text());jaw=json.loads((OUT/'attempt03/jaw-screen.json').read_text())
handoff={'status':'Bounded local head-form improvement proposal; whole likeness HOLD.','selectedAttempt':'attempt03','sourcePath':'scripts/regions/whole-character-v30-head-form.py','sourceSHA256':final['sourceSHA256'],'nativePath':'attempt03/head-form.blend','nativeSHA256':final['nativeSHA256'],'changedMeshes':final['result']['changedMeshes'],'changedNodes':final['result']['changedNodes'],'primaryPivotsChanged':[],'added':[],'removed':[],'contacts':{'jawPoseAngles':[p['jawNativeXDelta'] for p in jaw['poses']],'strictPairCounts':[p['strictPairCount'] for p in jaw['poses']],'inheritedIdentities':[['Forked forged mandible -1','Coaxial mandible journal'],['Forked forged mandible 1','Coaxial mandible journal.001']],'newPairs':[],'capClosedOpenStrictPairCounts':[p['strictPairCount'] for p in screen['poses']['candidate'] if p['pose']=='cap'],'limitations':screen['method']},'eraScope':screen['opticEraEvidence'],'materialDefinitionsExact':final['materialsExact'],'saveReopenExact':final['saveReopenExact'],'visibleRemainingDefects':['Broad smooth nasal face still simpler than reference formed hook.','Regular posterior crown course curtain and visible original dorsal fore-course step.','Large jaw journal/horizontal bearing bar and plain facade still dilute head identity.'],'actualViewsInspected':['attempt03/whole.png','attempt03/head.png','attempt03/jaw-open.png','attempt03/cap-open.png','attempt03/maker-head.png'],'priorFailuresPreserved':{'attempt01':'First coarse bill/forehead proposal; large flat optic aperture.','attempt02':'Optic seating improvement but bridge/hook rest+.08 crossing and two cap/temporal rest crossings.','attempt03':'Bridge reseated at paired jaw midspan and exact original dorsal courses1/2 retained; no new tested crossings.'},'baseNativeReferencedNotCopied':'assets/models/whole-character-v29/attempt-fit01/murderbird-whole-character-v29.blend','baseSHA256':final['baseSHA256']}
(OUT/'handoff.json').write_text(json.dumps(handoff,indent=2)+'\n')
files=[{'path':str(p.relative_to(OUT)),'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(OUT.rglob('*')) if p.is_file()];manifest={'sourceSHA256':final['sourceSHA256'],'selectedNativeSHA256':final['nativeSHA256'],'baseSHA256':final['baseSHA256'],'files':files,'baseBinaryDuplicated':False,'scope':'Own regional source, executed inputs, study natives/images/receipts/screen witnesses only; no publication/runtime selection change.'};(OUT/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n');assert all(sha(OUT/f['path'])==f['sha256'] and (OUT/f['path']).stat().st_size==f['bytes'] for f in files);assert sha(ROOT/'scripts/regions/whole-character-v30-head-form.py')==final['sourceSHA256'];print(json.dumps({'path':str(OUT),'manifestSHA256':sha(OUT/'manifest.json'),'filesValidated':len(files),'handoffSHA256':sha(OUT/'handoff.json')}))
