from pathlib import Path
import bpy,bmesh,runpy,json,hashlib,shutil,math
from mathutils import Vector
ROOT=Path('/Users/okh/.codex/worktrees/review-regression/murderbird-uncaged');OUT=Path('/tmp/v30-head-form/attempt02');OUT.mkdir(exist_ok=False);BASE=ROOT/'assets/models/whole-character-v29/attempt-fit01/murderbird-whole-character-v29.blend';SRC=ROOT/'scripts/regions/whole-character-v30-head-form.py';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();assert sha(BASE)=='04040543c39e98dd3d20da3d51a5ba40fd87151315ef074d328276eed97c63e7';bpy.ops.wm.open_mainfile(filepath=str(BASE));bpy.context.view_layer.update();h=runpy.run_path(str(ROOT/'scripts/build-uncaged-alignment-v7.py'));mats={m.name:h['material_signature'](m) for m in bpy.data.materials};shutil.copyfile(SRC,OUT/'executed-head-form.py');shutil.copyfile(__file__,OUT/'executed-study.py');module=runpy.run_path(str(OUT/'executed-head-form.py'));result=module['apply']();after=h['scene_snapshot']();assert mats=={m.name:h['material_signature'](m) for m in bpy.data.materials}
solids=[];dg=bpy.context.evaluated_depsgraph_get();points=[]
for n in result['changedMeshes']+result['added']:
 o=bpy.data.objects[n];ev=o.evaluated_get(dg);m=ev.to_mesh();v=[ev.matrix_world@v.co for v in m.vertices];assert all(math.isfinite(c) for p in v for c in p);points+=v;bm=bmesh.new();bm.from_mesh(m);closed=all(e.is_manifold for e in bm.edges);volume=bm.calc_volume(signed=True);bm.free();cp=m.copy();repair=cp.validate(verbose=False);bpy.data.meshes.remove(cp);solids.append({'name':n,'closed':closed,'signedVolume':volume,'validateRepair':repair,'evaluatedBounds':[[min(p[k] for p in v) for k in range(3)],[max(p[k] for p in v) for k in range(3)]]});ev.to_mesh_clear()
assert all(s['closed'] and s['signedVolume']>0 and not s['validateRepair'] for s in solids),[s for s in solids if not s['closed'] or s['signedVolume']<=0 or s['validateRepair']]
assert all(-.32<p.x<.32 and -.85<p.y<.05 and 1.35<p.z<2.10 for p in points)
bpy.context.preferences.filepaths.save_version=0;native=OUT/'head-form.blend';bpy.ops.wm.save_as_mainfile(filepath=str(native),check_existing=False);bpy.ops.wm.open_mainfile(filepath=str(native));assert h['scene_snapshot']()==after;assert sha(BASE)=='04040543c39e98dd3d20da3d51a5ba40fd87151315ef074d328276eed97c63e7'
r={'baseSHA256':sha(BASE),'sourceSHA256':sha(SRC),'nativeSHA256':sha(native),'rendererSHA256':sha(Path(__file__)),'result':result,'finiteSolids':solids,'materialsExact':True,'saveReopenExact':True,'views':[]};(OUT/'receipt.json').write_text(json.dumps(r,indent=2)+'\n')
scene=bpy.context.scene
for o in bpy.data.objects:
 if o.animation_data:o.animation_data_clear()
 if o.type=='MESH':o.hide_render='builder' not in o.get('exteriorEras','maker,mechanic,builder').split(',')
 elif o.type=='CURVE':o.hide_render=True
scene.render.engine='BLENDER_WORKBENCH';s=scene.display.shading;s.light='STUDIO';s.studio_light='paint.sl';s.color_type='SINGLE';s.single_color=(.56,.58,.60);s.show_shadows=False;s.show_cavity=True;s.cavity_type='BOTH';s.background_type='WORLD';scene.world.color=(.12,.13,.14);scene.render.resolution_x=scene.render.resolution_y=900;scene.render.resolution_percentage=100;scene.render.image_settings.file_format='PNG';d=bpy.data.cameras.new('V30 temporary head study');d.type='ORTHO';cam=bpy.data.objects.new(d.name,d);scene.collection.objects.link(cam);scene.camera=cam
for label,pos,target,scale,jaw in [('whole',(-6,-3.5,2.75),(0,-.08,1.02),2.5,0),('head',(-6,-2.4,2.15),(0,-.50,1.77),.95,0),('side',(-6,-.50,1.77),(0,-.50,1.77),.95,0),('jaw-open',(-6,-2.4,2.15),(0,-.50,1.77),.95,.32),('front',(0,-6,1.9),(0,-.50,1.77),.95,0)]:
 bpy.data.objects['jaw'].rotation_euler.x=jaw;bpy.context.view_layer.update();cam.location=pos;cam.rotation_euler=(Vector(target)-cam.location).to_track_quat('-Z','Y').to_euler();d.ortho_scale=scale;scene.render.filepath=str(OUT/(label+'.png'));bpy.ops.render.render(write_still=True);r['views'].append({'name':label,'path':scene.render.filepath,'sha256':sha(Path(scene.render.filepath)),'jawNativeX':jaw,'camera':{'position':pos,'target':target,'orthoScale':scale}});(OUT/'receipt.json').write_text(json.dumps(r,indent=2)+'\n')
print(json.dumps({'sourceSHA256':r['sourceSHA256'],'nativeSHA256':r['nativeSHA256'],'solids':len(solids),'changed':len(result['changedMeshes']),'added':len(result['added']),'removed':len(result['removed'])}))
