from pathlib import Path
import bpy,bmesh,runpy,json,hashlib,shutil,math
from mathutils import Vector
ROOT=Path('/Users/okh/.codex/worktrees/review-regression/murderbird-uncaged');OUT=Path('/tmp/v31-head-reconstruction/attempt05-fit-c');OUT.mkdir(exist_ok=False);BASE=ROOT/'assets/models/whole-character-v30/attempt-form02/murderbird-whole-character-v30.blend';SRC=ROOT/'scripts/regions/whole-character-v31-head-reconstruction.py';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();assert sha(BASE)=='207e32fe640fcc5cc9d3bef7bea4e07d302ec5bc06cc6642075df144d295e275';bpy.ops.wm.open_mainfile(filepath=str(BASE));bpy.context.view_layer.update();h=runpy.run_path(str(ROOT/'scripts/build-uncaged-alignment-v7.py'));materials={m.name:h['material_signature'](m) for m in bpy.data.materials};shutil.copyfile(SRC,OUT/'executed-head-reconstruction.py');shutil.copyfile(__file__,OUT/'executed-study.py');result=runpy.run_path(str(OUT/'executed-head-reconstruction.py'))['apply']();after=h['scene_snapshot']();assert materials=={m.name:h['material_signature'](m) for m in bpy.data.materials};bpy.context.preferences.filepaths.save_version=0;native=OUT/'head-reconstruction.blend';bpy.ops.wm.save_as_mainfile(filepath=str(native),check_existing=False);bpy.ops.wm.open_mainfile(filepath=str(native));assert h['scene_snapshot']()==after
r={'baseSHA256':sha(BASE),'sourceSHA256':sha(SRC),'nativeSHA256':sha(native),'rendererSHA256':sha(Path(__file__)),'result':result,'materialsExact':True,'saveReopenExact':True,'views':[]};(OUT/'receipt.json').write_text(json.dumps(r,indent=2)+'\n');scene=bpy.context.scene
for o in bpy.data.objects:
 if o.animation_data:o.animation_data_clear()
 if o.type=='MESH':o.hide_render='builder' not in o.get('exteriorEras','maker,mechanic,builder').split(',')
 elif o.type=='CURVE':o.hide_render=True
scene.render.engine='BLENDER_WORKBENCH';s=scene.display.shading;s.light='STUDIO';s.studio_light='paint.sl';s.color_type='SINGLE';s.single_color=(.56,.58,.60);s.show_shadows=False;s.show_cavity=True;s.cavity_type='BOTH';s.background_type='WORLD';scene.world.color=(.12,.13,.14);scene.render.resolution_x=scene.render.resolution_y=900;scene.render.resolution_percentage=100;scene.render.image_settings.file_format='PNG';d=bpy.data.cameras.new('V31 temporary profile review');d.type='ORTHO';cam=bpy.data.objects.new(d.name,d);scene.collection.objects.link(cam);scene.camera=cam;jawrest=bpy.data.objects['jaw'].rotation_euler.copy();caprest=bpy.data.objects['cranial-cover'].location.copy();origin=bpy.data.objects['head'].matrix_world.translation.copy();focus=origin+Vector((0,-.13,.215))
views=[('whole',(-6,-3.5,2.75),(0,-.08,1.02),2.5,0,0)]
for state,j in [('closed',0),('open',.32)]:
 for label,offset in [('head',(-6,-2.4,.42)),('side',(-6,0,0)),('front',(0,-6,.12))]:views.append((state+'-'+label,focus+Vector(offset),focus,.95,j,0))
views.append(('cap-open',focus+Vector((-6,-2.4,.42)),focus,.95,0,.08))
for label,pos,target,scale,jaw,cap in views:
 bpy.data.objects['jaw'].rotation_euler=jawrest;bpy.data.objects['jaw'].rotation_euler.x+=jaw;bpy.data.objects['cranial-cover'].location=caprest;bpy.data.objects['cranial-cover'].location.z+=cap;bpy.context.view_layer.update();cam.location=pos;cam.rotation_euler=(Vector(target)-cam.location).to_track_quat('-Z','Y').to_euler();d.ortho_scale=scale;scene.render.filepath=str(OUT/(label+'.png'));bpy.ops.render.render(write_still=True);r['views'].append({'name':label,'sha256':sha(Path(scene.render.filepath)),'camera':{'position':list(pos),'target':list(target),'orthoScale':scale},'jawNativeX':jaw,'capNativeZ':cap});(OUT/'receipt.json').write_text(json.dumps(r,indent=2)+'\n')
assert sha(BASE)==r['baseSHA256'] and sha(native)==r['nativeSHA256'];print(json.dumps({'sourceSHA256':r['sourceSHA256'],'nativeSHA256':r['nativeSHA256'],'reconstructedMeshes':len(result['reconstructedMeshes']),'removed':len(result['removed']),'newAdded':len(result['added']),'changedNodes':result['changedNodes']}))
