from pathlib import Path
import hashlib,json,shutil
ROOT=Path('/Users/okh/.codex/worktrees/review-regression/murderbird-uncaged');OUT=ROOT/'assets/audit/whole-character-v33/attempt-form06/era-integration';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def art(p):return {'path':str(p.relative_to(ROOT)),'bytes':p.stat().st_size,'sha256':sha(p)}
assert not (OUT/'receipt.json').exists() and not (OUT/'manifest.json').exists()
r=json.loads((OUT/'integration.json').read_text());comp=json.loads((OUT.parent/'receipt.json').read_text())
assert r['input']['sha256']=='7430fd397ad44e066e4f9197b023ba2f0f239451e12cb256ba34de8d9d4148ad';assert sha(ROOT/r['input']['path'])==r['input']['sha256'];assert sha(ROOT/comp['native']['path'])=='5fdfe66693db848fcf624b28484c3eaba220a8d7f389248390a4f21a571d108d'
sources=[]
for row in r['executedSources']:
 p=Path(row['path']);p=p if p.is_absolute() else ROOT/p;assert sha(p)==sha(OUT/row['frozenPath'])==row['sha256'];sources.append({'source':str(p.relative_to(ROOT)),'frozen':row['frozenPath'],'sha256':row['sha256'],'sourceUnchanged':True})
samples=r['scenarios'];maker=[m for s in samples for m in s['maker']];seats=[c for s in samples for c in s.get('cervicalSurfaceSeats',[])];motion={s['label'].split('-')[1]:s['physicalGeometryMotion'] for s in samples if 'physicalGeometryMotion' in s}
measurements={'maximumDeclaredSurfaceDistanceM':{id:max(m['authoredSurfaceDistance']['distanceM'] for m in maker if m['control']==id and 'authoredSurfaceDistance' in m) for id in ['jaw','wing']},'declaredSurfaceNames':{id:sorted({m['declaredSurfaceName'] for m in maker if m['control']==id and 'declaredSurfaceName' in m}) for id in ['jaw','wing']},'maximumCervicalSurfaceDistanceM':{'body':max(c['nearestBodySurface']['distanceM'] for c in seats),'neck':max(c['nearestNeckSurface']['distanceM'] for c in seats)},'cervicalSurfaceIdentities':sorted({c[key]['object'] for c in seats for key in ['nearestBodySurface','nearestNeckSurface']}),'maximumControlTrackingErrorM':max(m['trackingErrorM'] for m in maker),'maximumMechanismEndpointErrorM':max(v for s in samples for v in s['endpointErrors'].values()),'jawMaximumRad':max(s['jawAngleRad'] for s in samples),'jawReturnRad':next(s['jawAngleRad'] for s in samples if s['label']=='maker-jaw-return'),'actualControlGeometryMotion':motion,'advancedSourceVisibleCountByEra':{era:max(len(s['materialEraVisibility']['sourceAdvancedMeshesVisible']) for s in samples if s['era']==era) for era in ['maker','mechanic','builder']},'restUnchangedGroupOrigins':samples[0]['groupSeats']}
receipt={'status':'Bounded actual V33 Form06 controller/motion/mechanism/inspection/reset integration complete; whole fit and artistic acceptance remain separate','input':art(ROOT/r['input']['path']),'native':art(ROOT/comp['native']['path']),'compositionRegions':[x['source'] for x in comp['regions']],'summary':r['summary'],'measurements':measurements,'socketMetadata':r['metadata']['ownerSockets'],'activeLayout':r['metadata']['initialMechanismLayout'],'sourceChecks':sources,'arguments':{'model':r['input']['path'],'expectedSHA256':r['input']['sha256'],'output':str(OUT.relative_to(ROOT))},'limits':r['limits']+['V31-named harness resolves actual declared socket mesh names dynamically; no historical script change or runtime edit.','Nearest group-origin distances are not socket or supporting-interface proof; preserved apparatus fit and routing remain unaccepted.','No geometry/material-definition/model edits in this verification.']}
(OUT/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n');shutil.copy2(__file__,OUT/'executed-freeze.py');shutil.copy2('/tmp/v33-form06-era-integration.log',OUT/'integration.log')
shutil.copy2(OUT.parent/'receipt.json',OUT/'executed-composition-receipt.json')
files=[{'path':p.relative_to(OUT).as_posix(),'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(OUT.rglob('*')) if p.is_file()];assert all(sha(OUT/e['path'])==e['sha256'] for e in files)
for row in receipt['compositionRegions']:assert sha(ROOT/row['path'])==row['sha256']
(OUT/'manifest.json').write_text(json.dumps({'status':receipt['status'],'input':receipt['input'],'native':receipt['native'],'compositionRegions':receipt['compositionRegions'],'files':files,'relativePathHashesChecked':True},indent=2)+'\n')
print(json.dumps({'summary':r['summary'],'sourceSHA256':sources[0]['sha256'],'receiptSHA256':sha(OUT/'receipt.json'),'manifestSHA256':sha(OUT/'manifest.json'),'measurements':{k:v for k,v in measurements.items() if k not in ['actualControlGeometryMotion','restUnchangedGroupOrigins']},'motionM':{k:v['displacementM'] for k,v in motion.items()}},indent=2))
