"""Read-only actual rest endpoint and full exterior stock proof; not motion fit acceptance."""
import bpy,json,hashlib
from pathlib import Path
from mathutils import Vector
P=Path(__file__).resolve().parent;ROOT=P.parents[4];r=json.loads((P/'receipt.json').read_text());candidate=ROOT/r['outputs']['native']['path'];source=ROOT/r['inputs']['native']['path']
names=[f'V23 cervical {c} directional guard {g}'for c in range(1,5)for g in range(1,11)]+[f'V33 tapered throat cheek plate {s} {row} {c}'for s in[-1,0,1]for row in[0,1]for c in range(3)]
def sig(o):return hashlib.sha256(json.dumps({'v':[list(v.co)for v in o.data.vertices],'e':[list(e.vertices)for e in o.data.edges],'p':[(list(p.vertices),p.material_index,p.use_smooth)for p in o.data.polygons],'m':[m.name for m in o.data.materials]},sort_keys=True).encode()).hexdigest()
bpy.ops.wm.open_mainfile(filepath=str(source));before={n:{'signature':sig(bpy.data.objects[n]),'world':[list(x)for x in bpy.data.objects[n].matrix_world]}for n in names}
bpy.ops.wm.open_mainfile(filepath=str(candidate));bpy.context.view_layer.update();after={n:{'signature':sig(bpy.data.objects[n]),'world':[list(x)for x in bpy.data.objects[n].matrix_world]}for n in names};proof=[]
for a in r['contract']['attachmentAndEraMap']:
 if 'actualSourceInnerRootCoordinates'in a:
  o=bpy.data.objects[a['name']];v=[o.matrix_world@x.co for x in o.data.vertices];expected=[Vector(x)for x in a['actualSourceInnerRootCoordinates']];proof.append({'name':o.name,'source':a['sourceLeaf'],'finiteBackingOuterVertexCount':len(expected),'maximumRecordedRootCoordinateErrorM':max((v[i]-x).length for i,x in enumerate(expected)),'meaning':'Complete4x13grid outer receiving coordinates match actual source leaf inner root band at rest; point correspondence does not certify complete finite area seating or support strength.'})
 elif 'actualGuideRootQuad'in a:
  o=bpy.data.objects[a['name']];v=[o.matrix_world@x.co for x in o.data.vertices];q=[Vector(x)for x in a['actualGuideRootQuad']];target=[Vector(x)for x in a['terminalBackingQuad']];error=lambda b,c:max(min((x-y).length for y in c)for x in b);proof.append({'name':o.name,'rootSource':a['sourceGuideFace'],'rootQuadSetErrorM':error(v[:4],q),'terminalQuadSetErrorM':error(v[-4:],target),'meaning':'Actual finite link end corner sets agree with recorded distinct guide face/backinginner face; actual area/coplanar duplication/union quality not independently certified.'})
 elif 'actualRootQuad'in a:
  o=bpy.data.objects[a['name']];v=[o.matrix_world@x.co for x in o.data.vertices];q=[Vector(x)for x in a['actualRootQuad']];target=[Vector(x)for x in a['actualTerminalQuad']];error=lambda b,c:max(min((x-y).length for y in c)for x in b);proof.append({'name':o.name,'rootQuadSetErrorM':error(v[:4],q),'terminalQuadSetErrorM':error(v[-4:],target),'meaning':'Actual narrow journal-guide member corners correspond to actual named finite source faces; not contact-area or compoundyaw support PASS.'})
cover=bpy.data.objects['cervical-skull-cover'];head=bpy.data.objects['head'];out={'status':'Full58exterior/rest stock exact; endpoint coordinates qualified separately from FAILED moving fit','all58ExteriorMeshSignaturesExact':all(before[n]['signature']==after[n]['signature']for n in names),'all58RestWorldTransformsExact':all(before[n]['world']==after[n]['world']for n in names),'exactExteriorSignatures':{n:before[n]['signature']for n in names},'receiver':{'parent':cover.parent.name,'headParent':head.parent.name,'localCentreErrorM':(cover.matrix_local.translation-head.matrix_local.translation).length,'localPosition':list(cover.matrix_local.translation),'headshaftWorldCentre':list(head.matrix_world.translation),'sameRestOrientation':cover.matrix_local.to_quaternion().rotation_difference(head.matrix_local.to_quaternion()).angle},'endpoints':proof,'geometryDelta':'Zero exterior vertices/edges/faces moved/trimmed; all original paired skin walls exact. Nine lower throat identities reparented only; head/crown/jaw/optic unchanged. Two failed source headfans removed, other8retained. New27nodes include26supportmeshes+receiverempty.','transformRepair':'Depsgraph update added to closed()return before new guide/backing world reads. Defective receiver02 frozen separately. This is an implementation transform-read correction to second design, explicitly parent authorized; no design/shape change.','limits':['Actual receiving corner/grid correspondence does not cancel strict stock/skin/receiver-head/receiver-upper/yaw crossings or certify full area bearing contact.','Journal nominal1.5mm Xshaft radial clearance is not compound-yaw bearing acceptance.','No sourceframe/pivot movement; no silent geometry correction outside declared new supports.']}
(P/'attachment-proof.json').write_text(json.dumps(out,indent=2)+'\n');print('ATTACHMENT_PROOF',out['all58ExteriorMeshSignaturesExact'],out['all58RestWorldTransformsExact'],max(max(v for k,v in x.items()if k.endswith('ErrorM'))for x in proof))
