import json,hashlib,datetime
from pathlib import Path
ROOT=Path('/Users/okh/.codex/worktrees/cg-architect-cycle01/murderbird-uncaged')
A='assets/audit/cg-supervised01/attempt09/'
B='assets/audit/cg-supervised01/attempt09-baseline/'
S='assets/img/library/'
F='assets/audit/cg-supervised01/source-frames/'
source=[S+'murderbird-locked-sept22-composite-owner-reissued-2026-10-03.jpg','context/threads/assets/murderbird-camera-series-2026-09-05/murderbird-owner-preferred-july-reference.png',S+'murderbird-unified-master-candidate-03-2026-09-06.png',S+'murderbird-unified-maker-clean-candidate-2026-09-06.png',S+'murderbird-unified-mechanic-candidate-2026-09-06.png',S+'murderbird-unified-heart-candidate-2026-09-06.png']
frames=[F+'first-choice-'+x+'.png' for x in ['0-5s','2s','4s','6-5s']]
contacts=[A+era+'-source-before-candidate.jpg' for era in ['maker','mechanic','builder']]
details=[A+era+'/'+v+'.png' for era in ['maker','mechanic','builder'] for v in ['canon-neutral','head-neck','body-detail','feet-detail']]
turntables=[A+era+'-'+light+'-eight-views.jpg' for era in ['maker','mechanic','builder'] for light in ['neutral','workshop']]
browser=[A+'browser-'+era+'-'+mode+'.png' for era in ['maker','mechanic','advanced'] for mode in ['neutral','exhibit','illustrated']]+[A+'browser-advanced-'+mode+'.png' for mode in ['orbit','zoom','reset']]
extra=[A+'builder/'+v+'.png' for v in ['neutral-135','neutral-180','neutral-270','canon-workshop','side-profile']]+[B+'builder/'+v+'.png' for v in ['canon-neutral','head-neck','side-profile']]
viewed=source+frames+contacts+details+turntables+browser+extra
manifest=json.loads((ROOT/(A+'frozen-manifest.json')).read_text())
pins={f['path']:f['sha256'] for f in manifest['files']}
evidence={}
for i,p in enumerate(viewed,1):
 h=hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
 evidence[p]={'evidence_id':f'IMG-{i:02}','path':p,'sha256':h,'matches_frozen_manifest':h==pins[p],'inspection':'direct local image pixels via view_image; saved native render or saved actual browser screenshot, not newly generated'}
def refs(paths):return [evidence[p] for p in paths]
whole=[source[0],source[2]]+contacts+[A+'builder/canon-neutral.png',A+'builder/canon-workshop.png',A+'browser-advanced-neutral.png',A+'browser-advanced-exhibit.png']
head=[source[0],source[1],frames[0],B+'builder/head-neck.png',A+'builder/head-neck.png',A+'builder/neutral-180.png',A+'browser-advanced-orbit.png']
body=[source[0],source[2],frames[2],B+'builder/canon-neutral.png',A+'builder/body-detail.png',A+'builder/side-profile.png',A+'builder/neutral-270.png']
feet=[source[0],frames[0],A+'maker/feet-detail.png',A+'mechanic/feet-detail.png',A+'builder/feet-detail.png',B+'builder/canon-neutral.png',A+'builder/canon-neutral.png']
era=source[3:]+[A+e+'/canon-neutral.png' for e in ['maker','mechanic','builder']]+[A+e+'/head-neck.png' for e in ['maker','mechanic','builder']]+[A+'browser-'+e+'-'+l+'.png' for e in ['maker','mechanic','advanced'] for l in ['neutral','exhibit']]
criteria=[
 {'criterion_id':'C00','verdict':'reject','evidence_status':'analytical','finding':'Full09 is not the completed source-aligned photoreal three-era target. Normal whole-display images show persistent compactness, head/construction, foot mass and era finish gaps. Owner acceptance is independently absent and cannot be granted by this role.','direct_image_evidence':refs(whole)},
 {'criterion_id':'C01','verdict':'approve-with-limits','evidence_status':'analytical','finding':'Meaningful but mixed incremental study gain is visible: throat into breast has coherent overlapping rows instead of loose isolated scales; Advanced optic reads as a smaller recessed amber lens rather than the earlier flat large ring pattern. This does not establish whole-source alignment, and the broad smooth breast panels and pale forehead panel create competing source mismatches.','direct_image_evidence':refs(contacts+[B+'builder/head-neck.png',A+'builder/head-neck.png',B+'builder/side-profile.png',A+'builder/side-profile.png',A+'browser-advanced-neutral.png'])},
 {'criterion_id':'C02','verdict':'reject','evidence_status':'analytical','finding':'Coherence is only partial. Shield is compact and birdlike, but head/crown remains sparse coarse construction; cheek framing is a few smooth bars rather than source nested plates/fasteners; the vertically elongated breast flows into a narrow point rather than compact source chest; feet retain flat dorsal cover strips and smooth short talons instead of individually substantial segmented toes. Rear/native and browser orbit show an obvious open empty-looking head/neck shell. These are visible defects; unknown source rear depth is not a license to assert an unseen reference shape.','direct_image_evidence':refs(head+body+feet)},
 {'criterion_id':'C03','verdict':'reject','evidence_status':'analytical','finding':'Same inherited silhouette is supported and the visible optic rule passes: Maker/Mechanic centers remain dark, Advanced has restrained readable amber at whole scale. Full era finish distinction fails visually: Maker and Mechanic look nearly identical at normal scale, and Advanced changes chiefly in optic. Source-specific new/aged/repaired/inherited regional character is not legible enough. The bright pale gold brow competes with the Advanced optic rather than following the source focal hierarchy. Nonemission data itself was not inspected in this role.','direct_image_evidence':refs(era)},
 {'criterion_id':'C04','verdict':'defer-for-evidence','evidence_status':'not-run','finding':'Native original payload, graph, packed image and anchor preservation is outside this outcome image review. Pixels cannot prove byte preservation. Route to independent evidence role; no preservation pass inferred.','direct_image_evidence':[]},
 {'criterion_id':'C05','verdict':'defer-for-evidence','evidence_status':'not-run','finding':'Saved actual browser screenshots visibly show the candidate, but editability, UV/material equivalence, finite indices and forbidden payload absence require data inspection. This role did not reopen natives or parse GLBs.','direct_image_evidence':refs([A+'browser-maker-neutral.png',A+'browser-mechanic-neutral.png',A+'browser-advanced-neutral.png'])},
 {'criterion_id':'C06','verdict':'approve-with-limits','evidence_status':'analytical','finding':'The inspected frozen packet provides source/before/candidate contacts, direct native whole/head/body/feet, neutral and workshop eight-angle contacts for every era, plus saved desktop WebGL/fallback/control images. Hash verification ties inspected pixels to the frozen manifest. Browser controls are evidenced by distinct orbit/zoom/reset captures, not by live interaction in this role. Mobile, performance, accessibility, motion and deployment are not established.','direct_image_evidence':refs(contacts+turntables+browser)}
]
claims=[
 {'claim_id':'CLM09-00','status':'disputed','verdict':'reject','claim':'Full09 meets the completed source-aligned photoreal three-era modeling target','finding':'Direct visible material failures survive. The owner artistic gate is also absent.','direct_image_evidence':refs(whole+era)},
 {'claim_id':'CLM09-01','status':'supported-with-limits','verdict':'approve-with-limits','claim':'Full09 visibly improves complete source character rather than only technical completion','finding':'Connected front layering and optic recession are visible, useful study changes. Overall source convergence is partial and mixed; do not describe the complete character as target achieved.','direct_image_evidence':refs(contacts+[B+'builder/head-neck.png',A+'builder/head-neck.png'])},
 {'claim_id':'CLM09-02','status':'blocked-in-this-role','verdict':'defer-for-evidence','claim':'All three receiving native originals/maps/graphs/anchors survive integration','finding':'Not tested by the outcome role; no conclusion from image appearance.','direct_image_evidence':[]},
 {'claim_id':'CLM09-03','status':'provisional','verdict':'defer-for-evidence','claim':'Static GLBs retain native active UV/material data and load actual Chrome','finding':'The saved actual-browser image component is visually supported. Retained data and current live loading were not independently tested by this role.','direct_image_evidence':refs([A+'browser-maker-neutral.png',A+'browser-mechanic-neutral.png',A+'browser-advanced-neutral.png'])},
 {'claim_id':'CLM09-04','status':'supported-with-limits','verdict':'approve-with-limits','claim':'Maker/Mechanic remain dark and Advanced awakening reads at whole scale','finding':'Supported visually across native and saved browser neutral/exhibit pixels. This establishes the visible optic rule, not full era finish distinction or emission data correctness.','direct_image_evidence':refs(era)},
 {'claim_id':'CLM09-05','status':'disputed','verdict':'reject','claim':'Regional retained gains remain useful when combined; declared tip/optic limitations do not cause a material whole-character regression','finding':'Useful gains survive, but an unqualified no-material-regression claim is too strong: the new bright plain brow steals attention, broad smooth breast subdivision loses source layered fastener rhythm, and dorsal foot cover reduces articulated toe reading. Those mixed changes must remain explicit.','direct_image_evidence':refs(head+body+feet)},
 {'claim_id':'CLM09-06','status':'supported-with-limits','verdict':'approve-with-limits','claim':'Delivery evidence, pinned-source and runtime-boundary claims correspond to actual frozen resources','finding':'Contract and manifest hashes match supplied pins; all 119 manifest image/criteria/claim/goal resources hash-match. Only 55 listed images were visually inspected. The entire 216-file resource set and runtime build/deployment claims were not checked here.','direct_image_evidence':refs(source+frames+contacts)}
]
report={
 'schema_version':'1.0','role':'outcome','reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),
 'artifact_root':str(ROOT),'artifact':'Full09 three-era native/static GLB development review study',
 'question':'Can full09 be treated as the completed source-aligned photoreal three-era MurderBird model? Distinguish admissible review-study delivery from that target claim.',
 'review_contract':{'path':A+'review-contract.json','sha256':'e2655b700d8cae824c8dafebcc1ca71a80b9d284cf7808d42a44d4172d6ac899','verified':True},
 'frozen_manifest':{'path':A+'frozen-manifest.json','sha256':'378a01fb9430ade08c9de4c5bcc2026f9130bda95d8d57d237390bf12e748c36','file_count':216,'verified_manifest_hash':True,'verified_image_criteria_claim_goal_resource_hashes':119,'verified_full_manifest_resources':False},
 'goal':{'path':'goal.md','sha256':'31bc42e668e5fed1769a1956c5f97bef726c6d4d8accdb303c63e77ccc5202b5','local_frozen_goal_read':True,'latest_shared_main_revision_source_reported_by_contract':'251f2f0243181e97140179c2aff6eb057e165438','remote_goal_independently_fetched_in_this_role':False},
 'verdict':'reject','verdict_scope':'Reject completed source-aligned photoreal target claim. Do not reject preservation of this useful study.',
 'study_delivery_verdict':'approve-with-limits','study_delivery_conditions':['Label as an unaccepted mixed incremental review study.','Carry every stated source, head-shell, breast-flow, foot and era-finish defect forward.','Evidence and portability roles must independently settle technical custody/delivery gates.','No runtime promotion, deployment, animation or engineering inference follows from this review.'],
 'target_vs_study':{'target_success':False,'meaningful_study_gain':True,'whole_bird_source_convergence':'partial and mixed','owner_artistic_acceptance':False,'technical_pass_establishes_likeness':False},
 'criteria':criteria,'claims':claims,
 'observed_gains':[{'finding':'Connected throat/breast plate overlap restores a deliberate front armor flow; before06 loose scales and large throat interruption are reduced.','direct_image_evidence':refs([B+'builder/canon-neutral.png',A+'builder/canon-neutral.png',B+'builder/head-neck.png',A+'builder/head-neck.png'])},{'finding':'Advanced lens is more convincingly recessed and its amber has a smaller readable center at whole scale. Maker/Mechanic stay visibly dark.','direct_image_evidence':refs([B+'builder/head-neck.png',A+'builder/head-neck.png',A+'maker/head-neck.png',A+'mechanic/head-neck.png',A+'browser-advanced-neutral.png'])},{'finding':'New dorsal foot cover adds visible exterior mass, although its flattened pad reading is a source-specific regression rather than resolved foot likeness.','direct_image_evidence':refs([B+'builder/canon-neutral.png',A+'builder/canon-neutral.png',A+'builder/feet-detail.png'])}],
 'observed_regressions':[{'finding':'Large bright plain brow panel dominates the face and lacks source contour/subdivision/fastener rhythm; it competes with optic focus.','direct_image_evidence':refs(head[:5])},{'finding':'Broad smooth long breast panels replace fine isolated scales but reduce source dense riveted layering and exaggerate a narrow tapered front.','direct_image_evidence':refs(body)},{'finding':'Dorsal foot cover flattens/bridges toe volume; individual articulated heavy source toes and claws remain absent.','direct_image_evidence':refs(feet)}],
 'strongest_remaining_defect':{'finding':'Whole-character construction hierarchy remains visibly unlike the locked canon: a tall narrow tapering front and sparse/open coarse head shell replace the compact densely layered bird. Material smoothing and brighter brow do not restore that likeness.','criterion':'C00/C02','direct_image_evidence':refs(whole+[A+'builder/neutral-180.png',A+'browser-advanced-orbit.png'])},
 'smallest_decisive_next_check':{'purpose':'A next development gate, not a missing prerequisite to reject the current completion claim.','check':'After one bounded correction to the front/head construction hierarchy, show the pinned locked source and scoped July head beside immutable06 and the corrected candidate at the existing same camera, matched bird height and neutral lighting. Review at normal full-bird display scale plus one head crop, then one rear135/180 view for visible shell continuity. Accept only if source compactness and focal construction improve without hiding feet or losing era optics. No new lighting/exposure change should be used to obscure the discrepancy.','owner':'Integrator plus owner artistic review','unseen_reference_limit':'Do not infer source rear construction; the rear view only checks visually distracting candidate incompleteness.'},
 'independence':{'model_family':'Shared Sol family per frozen contract','context':'Separate role prompt and local visual inspection; no children','development_set':'All pinned sources were seen during optimization; no protected holdout','holdout':'absent','other_current_role_outputs_read':False,'producer_summaries_read':False,'producer_claim_ledger_read_after_own_notes':True,'own_notes_path':'/tmp/cg-eq09-outcome-own-visual-notes.json','memory_context_exposure':'Developer-required quick memory registry search surfaced older September visual-review snippets before image work. No rollouts or history verdict files were opened. Those snippets are not evidence for this verdict; all material findings are tied to current pinned pixels. This limits any claim of perfectly fresh context.','agreement_limit':'Shared model/source/development references make reviewer agreement correlated, not external validation.'},
 'execution':{'evidence_status':'analytical','inspected_images':len(viewed),'inspection_method':'view_image direct saved local pixels','saved_browser_screenshots_inspected':True,'live_browser_interaction':False,'native_reopen_or_GLb_data_inspection':False,'render_test':'not-run','tests':['Contract and manifest SHA256 verification','SHA256 readback of 119 frozen image/criteria/claim/goal resources; no mismatches','Direct source-first review of 55 images before producer summaries or regional QA'], 'mutated_judged_artifacts':False,'git_actions':False,'publication':False,'outputs_only_in_tmp':True},
 'limitations':['Camera estimated and source depth unknown; source alignment precision is limited but visible mismatches remain binding.','Approved fixed pose is respected; no stance change is applied or required by this report, and held pose does not imply target match.','Native and browser lighting/tone mapping differ; no pixel parity claim.','Source frames support static screen-presence judgment, not motion validation.','Native editability/preservation and GLB material-data fidelity not tested by this outcome role.','Mobile/performance/accessibility/deployment are not tested.','Owner artistic acceptance remains a separate required gate.'],
 'direct_image_evidence':list(evidence.values()),'review_expiry_trigger':'Any change to frozen image/model resources, camera, pose, materials or lighting, or receipt of owner artistic direction requires a new scoped review.'
}
# Keep the reported visual count exact rather than copying a prose estimate.
for c in report['claims']:
 if c['claim_id']=='CLM09-06':c['finding']=c['finding'].replace('55 listed images',str(len(viewed))+' listed images')
report['execution']['tests'][-1]=report['execution']['tests'][-1].replace('55 images',str(len(viewed))+' images')
Path('/tmp/cg-eq09-outcome.json').write_text(json.dumps(report,indent=2)+'\n')
print('report',len(viewed),'visually inspected images',Path('/tmp/cg-eq09-outcome.json').stat().st_size,'bytes')
print('SHA256',hashlib.sha256(Path('/tmp/cg-eq09-outcome.json').read_bytes()).hexdigest())
