import json,pathlib,hashlib,datetime
prefix='/tmp/cg-recursive-loop01-final-evidence'
post=json.load(open(prefix+'-postcheck.json'));native=json.load(open(prefix+'-native.json'));binding=json.load(open(prefix+'-bindings.json'));rig=json.load(open(prefix+'-rig.json'));views=json.load(open(prefix+'-view-check.json'))
proofs=[]
for suffix in ['-native.py','-native.json','-native.log','-bindings.py','-bindings.json','-bindings.log','-rig.py','-rig.json','-rig.log','-view-check.json','-postcheck.json']:
 p=pathlib.Path(prefix+suffix);proofs.append({'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
r={'schema_version':1,'role':'independent evidence QA','reviewed_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'reviewer_context':'/root/closeout21_record_qc','decision':'approve-with-limits','decision_scope':'Retain BODY01 curvature direction conditionally as an editable/static development increment and use the mechanically complete limited packet to feed loop02. This does not confirm unqualified net whole-character source gain or owner acceptance.','visual_claim_decision':'L01-F01 partially supported, provisional; useful local breast-direction gain, important visible join/plate costs remain.','target_status':'Three-era source-aligned photoreal visual twin remains unmet; owner acceptance not substituted.',
'authority':{'goal_read':True,'owner_authorization_read':True,'loop_control_read':True,'goal_sha256':'31bc42e668e5fed1769a1956c5f97bef726c6d4d8accdb303c63e77ccc5202b5','owner_allowance':'10 hours / 1 billion tokens shared across three loops, fixed ten-agent team, no children; expired historical allowance superseded only','remote_main':'251f2f0243181e97140179c2aff6eb057e165438 historical; not freshly fetched by reviewer'},
'custody':post,
'claim_reviews':[
 {'id':'L01-F01','status':'partially-supported / provisional interpretation','decision':'retain-with-limits direction; do not mark whole-character net gain across all eras without important regressions confirmed','evidence':'Actual source images inspected before producer claim review; all three paired canon-neutral and canon-workshop wholes inspected. Advanced paired neutral eight angles and candidate workshop eight angles plus selected workshop baseline comparisons inspected. BODY01 replaces elongated longitudinal breast with shorter rounded courses; useful avian breast direction is visible across era wholes.','costs':['Broad repeated plates read padded/puffy, with regular teardrop scale pattern rather than varied flatter formed-metal courses visible in sources.','Upper throat-to-breast side joins expose a dark wedge more prominently after original continuous breast panels are hidden (neutral/workshop 045,090,270,315).','Front/lower breast has dark triangular breaks and suspended lower join around the hip, especially workshop000/090/315.','Inherited head proportions, rear/top-neck opening, era finish differentiation and stance/source matching remain unresolved. Rear source depth is not calibrated; do not invent a rear acceptance claim.'],'confidence':'moderate for local rounded-breast direction; lower for overall net three-era likeness judgment'},
 {'id':'L01-F02','status':'confirmed within independently checked fields','decision':'PASS with declared exclusions','evidence':'Nine native files opened read-only: original09, matched02, retained02 for all eras. Original receiving mesh/empty payloads, checked material graphs, packed FILE bytes and metadata preserved. Each matched02 has zero receiving changes; each retained02 has zero receiving changes except exact34 declared visibility retirements and36 added BODY meshes. 7608 becomes7644 mesh/empty;62 materials;161 Advanced or160 Maker/Mechanic packed FILE images. Additional independent camera/light/armature/world/unit comparison has zero changes.','limits':['Transient session_uid and material reference-count users excluded from preservation comparison.','Non-ID pointer substructure internals and nested shader-group internals not exhaustively compared.','Receiving mesh control topology/UV/attributes/slots/face indices/modifier RNA and transforms checked; full evaluated modifier output equivalence is not claimed.','Counts corroborate direct comparisons and do not establish appearance.']},
 {'id':'L01-F03','status':'confirmed custody and substantial static export correspondence, with explicit limits','decision':'PASS for limited development packet','evidence':'All69 paired saved view specs match camera/light/resolution/samples/material override;138 actual PNG dimensions and hashes match receipts. Whole/turntable views1280x853, detail views1280square, hero960x1280;12 samples recorded. Three actual retained static GLBs independently decoded. Evaluated visible native material triangle counts and per-material world-space triangle-corner position multisets at1e-5 agree with GLBs; finite attributes, accessor/index bounds and material/UV-channel/texture reference bounds PASS. Embedded images match exact native packed bytes46/46 Advanced,45/45 Maker,45/45 Mechanic. No skins, animations or external URIs.','limits':['Rendering execution was not replayed; samples and rig declarations remain recorded producer execution evidence, supplemented by image custody and saved native rig checks.','Position/material multiset correspondence is not vertex-order or normal equivalence proof.','Exact native-to-GLB UV corner values and complete shader graph/renderer equivalence not independently replayed.','Exporter side-profile/native-browser tone difference is not pixel parity.']},
 {'id':'L01-F04','status':'producer observed/captured, independently inspected saved pixels and hashes; not independently live replayed','decision':'accept exact recorded browser scope only','evidence':'Root IAB browser-verification.json records all three WebGL models and neutral/exhibit lighting plus manual PNG fallback12 captures. Reviewer viewed saved all-era neutral and Advanced fallback-exhibit captures. Warm Advanced and dark Maker/Mechanic optic distinction is visible. Maker/Mechanic reset recorded; separate Advanced reset pending/not run.','limits':['No reviewer live browser run.','No forced WebGL failure, manual orbit/zoom, mobile/new-host, performance or browser/native pixel parity proof.','browser-static-validation.json is historical worker static evidence referring to retired retained01/matched09 delivery paths and incomplete delivery; later root final captures/current retained02 page support actual readiness. Do not cite the historical NOT READY snapshot as a fresh final readiness check.']},
 {'id':'L01-F05','status':'not achieved / not claimed','decision':'reject any completion upgrade','evidence':'Estimated sourcecamera and seen optimization references do not establish calibrated visual-twin accuracy; no owner likeness acceptance exists for this packet.'}
],
'native_summary':[{'era':x['era'],'kind':x['kind'],'counts':x['counts'],'receiving_changes':x['receiving_changes'],'visibility_change_count':len(x['visibility_changes']),'new_mesh_count':x['new_mesh_count']} for x in native['results']],
'rig_summary':rig['results'],
'glb_summary':[{'era':x['era'],'triangle_material_count_matches':x['triangle_material_count_matches'],'position_material_multiset_mismatches':x['world_triangle_corner_position_multiset_rounded1e5_mismatches'],'native_positions_and_all_UVs_finite':x['native_positions_and_all_UVs_finite'],'binding_bounds':x['GLB_attributes_indices_material_UV_texture_binding_bounds'],'embedded_images':len(x['images']),'exact_packed_matches':sum(y['native_packed_exact'] for y in x['images']),'skins':x['skins'],'animations':x['animations'],'external_URIs':x['external_URIs']} for x in binding['results']],
'local_build_status':{'producer_commands':'npm ci and npm run build reported PASS in frozen local-build-inspection.json; reviewer did not rerun commands','independently_current_dist':post['current_dist'],'runtime_glb':'Only originalV37 emitted runtime GLB; no BODY01 production promotion','CI_deployment_remote':'not run by reviewer; no remote/publication acceptance'},
'visual_coverage':{'direct_source_pixels':['assets/img/library/murderbird-locked-sept22-composite-owner-reissued-2026-10-03.jpg','assets/img/library/murderbird-unified-maker-clean-candidate-2026-09-06.png','assets/img/library/murderbird-unified-mechanic-candidate-2026-09-06.png','assets/img/library/murderbird-unified-heart-candidate-2026-09-06.png','context/threads/assets/murderbird-camera-series-2026-09-05/murderbird-owner-preferred-july-reference.png'],'direct_candidate_baseline_pixels':'All three era paired canon-neutral/canon-workshop wholes; Advanced matched/retained neutral000,045,090,135,180,225,270,315; Advanced retained workshop000,045,090,135,180,225,270,315 and matched workshop000,090,180,315; Advanced retained side-profile; saved browser all-era neutral and Advanced fallback-exhibit. Whole-source observations preceded producer claims.','limits':'Did not visually inspect every one of138 delivered PNGs or all three eras eight angles in both rigs. All138 received independent hash/dimension/spec checks. No video motion acceptance or protected holdout.'},
'necessary_corrections':[
 {'path':'assets/audit/cg-recursive-three-loop01/loop01/final-review-contract.json / resulting equilibrium decision','correction':'Adjudicate F01 as provisional/partially supported, retaining rounded BODY direction with explicit padded-plate and upper/lower join costs; do not equate technical PASS with whole-character likeness acceptance.','evidence_paths':['delivery/retained02/builder/workshop-000.png','delivery/retained02/builder/workshop-090.png','delivery/retained02/builder/workshop-315.png','delivery/matched02/builder/workshop-090.png']},
 {'path':'assets/audit/cg-recursive-three-loop01/loop01/browser-static-validation.json / resulting delivery evidence narrative','correction':'Label this frozen report historical and superseded in readiness scope by browser-verification.json; retain its bytes and distinguish producer IAB evidence from reviewer live replay.','severity':'evidence-label clarification, not a packet blocker'}
],
'smallest_next_task':'Loop02 should retain useful breast curvature while correcting upper throat-to-new-breast continuity and overly padded/repetitive plate treatment. Show same-camera whole neutral and workshop pairs with profile/front/three-quarter check before fastener/detail work; preserve immutable09 receiving payload and optic, and keep overall source-likeness/owner decision open.',
'independence_limits':['Separate read-only EVIDENCE role; independently authored native/GLB checks, no producer helper imports.','Same reused fixed-team context previously reviewed09 document closeout and early combined HEAD01+BODY01; not a fresh external blind reviewer.','Shared Sol model family, source images, Blender semantics and owner constraints create model/context correlation.','No other current QA role reports read.','Sources are optimization-seen, not a protected holdout; source camera/depth are estimated.','Old approved09 document decision supplies custody context only, not new visual acceptance.'],
'not_run':['New native saves, renders, exports or model edits','New npm commands or live reviewer browser interactions','Exact GLB UV-corner/normal equivalence or complete renderer/shader parity','Calibrated sourcecamera/depth reconstruction','Engineering, articulation/animation, physical prototype or load testing','Git changes/commit/push, remote CI/deployment/publication','Owner artistic acceptance','Children/subagent delegation'],
'probe_methodology_notes':['GLB position comparison uses Blender float32 world-coordinate transforms then GLTF Y-up swizzle; an initial NumPy float64 quantization mismatch disappeared under this precision-correct comparison and is not claimed as exporter defect.','SessionUID/material-user counters are runtime bookkeeping and excluded intentionally, not receiving authored-payload differences.'],
'proofs':proofs}
path=prefix+'.json';open(path,'w').write(json.dumps(r,indent=2)+'\n');print(path);print(hashlib.sha256(pathlib.Path(path).read_bytes()).hexdigest());print('claim decisions',[(x['id'],x['status']) for x in r['claim_reviews']]);print('custody',[(x['count'],len(x['mismatches'])) for x in post['manifests']])
