from pathlib import Path
import json,hashlib
ROOT=Path('/Users/okh/.codex/worktrees/review-regression/murderbird-uncaged');OUT=Path(__file__).parent;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();study=ROOT/'assets/audit/whole-character-v29/regional-studies/breast-hinge/attempt02';basepath=study/'base-opening-screen.json';priorpath=study/'opening-screen.json';currentpath=OUT/'opening-screen.json';base=json.loads(basepath.read_text());prior=json.loads(priorpath.read_text());new=json.loads(currentpath.read_text());native=ROOT/'assets/models/whole-character-v29/attempt-fit01/murderbird-whole-character-v29.blend';original=ROOT/'assets/models/whole-character-v28/attempt-form02/murderbird-whole-character-v28.blend';assert sha(native)==new['nativeSHA256']=='04040543c39e98dd3d20da3d51a5ba40fd87151315ef074d328276eed97c63e7';assert sha(original)==base['nativeSHA256']=='838a86b16766ddd4491c9f1cbe6a7aa0039c2b9e8514a04eb710d1e9b2f9bd9d';key=lambda a:tuple(sorted([a['source'],a['neighbor']]))
comparisons=[]
for b,p,n in zip(base['poses'],prior['poses'],new['poses']):
 assert b['breastLocalXDelta']==p['breastLocalXDelta']==n['breastLocalXDelta'];bs={key(a) for a in b['pairs']};ps={key(a) for a in p['pairs']};ns={key(a) for a in n['pairs']};assert n['hingeStrictPairs']==0;assert ns==ps and ns<=bs
 comparisons.append({'breastLocalNativeX':n['breastLocalXDelta'],'exactForm02AllPairs':b['strictPairCount'],'finalHingeStudyAllPairs':p['strictPairCount'],'exactCompositeAllPairs':n['strictPairCount'],'compositeHingePairs':n['hingeStrictPairs'],'removedForm02Pairs':[list(x) for x in sorted(bs-ns)],'introducedVsOriginal':[],'addedVsFinalHingeStudy':[],'remainingPairs':[list(x) for x in sorted(ns)]})
out={'status':'PASS exactcomposition bounded hinge crossing repair; wholebreast restFAIL and overallartHOLD','executedComparisonSHA256':sha(Path(__file__)),'exactCompositeNativeSHA256':sha(native),'exactOriginalNativeSHA256':sha(original),'originalBaseline':{'relativeToRepository':str(basepath.relative_to(ROOT)),'sha256':sha(basepath),'method':'Reuse preserved executed fivepose screen of exactForm02; nativehash reverified now, no redundant baseline rerun.'},'regionalHingeStudy':{'relativeToRepository':str(priorpath.relative_to(ROOT)),'sha256':sha(priorpath),'nativeSHA256':prior['nativeSHA256']},'newScreenSHA256':sha(currentpath),'sourceSHA256':new['sourceSHA256'],'comparisons':comparisons,'allFiveHingePairsZero':True,'noAddedNeighborPairIdentitiesAfterWingComposition':True,'restResidualCount':7,'limits':['Five breastopening samples; otherjoints atrest. No continuous, containment,min-distance, physics or wholemotion/artacceptance.','Seven exactoriginal upperbreast/neckroot restidentities remain; geometryoutsidehinge was not repaired bythisassignment.','Stricttriangle pair counts are not penetrationdepth.'],'openView':'open.png'};(OUT/'comparison.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'hingePairs':[p['hingeStrictPairs'] for p in new['poses']],'totalPairs':[p['strictPairCount'] for p in new['poses']],'introduced':0}))
files=[{'path':str(p.relative_to(OUT)),'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(OUT.iterdir()) if p.is_file() and p.name!='manifest.json'];(OUT/'manifest.json').write_text(json.dumps({'nativeSHA256':sha(native),'sourceSHA256':new['sourceSHA256'],'status':out['status'],'files':files},indent=2)+'\n');assert all(sha(OUT/x['path'])==x['sha256'] for x in files);print('manifestSHA256',sha(OUT/'manifest.json'))
