from pathlib import Path
import hashlib,json,shutil
ROOT=Path('/Users/okh/.codex/worktrees/review-regression/murderbird-uncaged');OUT=Path(__file__).parent;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def art(p):return {'path':str(p.relative_to(ROOT)),'bytes':p.stat().st_size,'sha256':sha(p)}
assert not(OUT/'manifest.json').exists();shutil.copy2('/tmp/v33-form01-neck-screen.log',OUT/'screen.log');shutil.copy2(OUT.parent/'receipt.json',OUT/'executed-composition-receipt.json');composition=json.loads((OUT/'executed-composition-receipt.json').read_text());native=ROOT/composition['native']['path'];assert sha(native)=='122076fb0faa92a78d800c6a97e1d8fcad9d3dd19f9a97693bdb26861a2df850';screen=json.loads((OUT/'screen.json').read_text());assert screen['nativeSHA256']==sha(native)
comparisons={}
for label,directory in [('v32','assets/audit/whole-character-v32/attempt-form01/neck-screen'),('regional','assets/audit/whole-character-v33/regional-studies/neck-guards/coarse01/neck-screen')]:
 source=ROOT/directory;shutil.copy2(source/'screen.json',OUT/f'executed-{label}-baseline-screen.json');shutil.copy2(source/'executed-screen.py',OUT/f'executed-{label}-baseline-validator.py');assert sha(source/'executed-screen.py')==sha(OUT/'executed-screen.py');b=json.loads((source/'screen.json').read_text());rows=[]
 for old,new in zip(b['poses'],screen['poses']):
  assert old['pose']==new['pose'] and old['angles']==new['angles'];op={tuple(sorted((r['a'],r['b']))) for r in old['pairs']};np={tuple(sorted((r['a'],r['b']))) for r in new['pairs']};rows.append({'pose':new['pose'],'angles':new['angles'],'baselineCount':old['pairCount'],'compositionCount':new['pairCount'],'inherited':sorted(op&np),'introduced':sorted(np-op),'eliminated':sorted(op-np)})
 comparisons[label]={'baselineNativeSHA256':b['nativeSHA256'],'baselineScreenSHA256':sha(source/'screen.json'),'sameValidatorBytes':True,'poses':rows}
for row in composition['regions']:assert sha(ROOT/row['source']['path'])==row['source']['sha256']
neck=next(row['source'] for row in composition['regions'] if 'neck-guards' in row['source']['path']);assert neck['sha256']=='de8f3854b3e631be5829505cb51836816e22d9166cf07e7f6cc6e4513b807f18'
receipt={'status':'Zero strict crossings in exact composition at seven poses; contact coverage gap remains visibly unresolved','native':art(native),'compositionRegionSources':[row['source'] for row in composition['regions']],'validator':art(OUT/'executed-screen.py'),'method':screen['method'],'comparisons':comparisons,'contactVisualObservation':{'status':'Matched-image visual observation, not a measured continuous coverage or attachment test','compositionImage':art(OUT/'contact-neck.png'),'baselineImage':art(ROOT/'assets/audit/whole-character-v33/regional-studies/neck-guards/coarse01/neck-screen/contact-neck.png'),'assessment':'Exposed structure gap between distal neck guard course and lower head hood remains visually about unchanged; no obvious worsening. Orbital02 changes add head-owned throat seam/profile detail above the opening. The opening is not closed or proven continuously protected.','camera':{'position':[-6,-3.5,2.45],'target':[0,-.27,1.48],'orthoScale':1.3,'resolution':[900,900],'engine':'BLENDER_WORKBENCH','studioLight':'paint.sl','castShadows':False}},'arguments':{'model':str(native.relative_to(ROOT)),'sha':sha(native),'output':str(OUT.relative_to(ROOT)),'render':True},'limits':['Strict finite edge/face crossings at seven discrete samples only. Not continuous collision/containment, same-owner geometry, force/support or engineering/art acceptance.','Zero crossings does not establish continuous protective coverage or visually connected head support.','No new geometry or runtime edits. Form02 jaw-bore repair not tested or implied by this Form01 binding.']}
assert all(p['pairCount']==0 for p in screen['poses']);(OUT/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n')
(OUT/'contact-coverage-observation.md').write_text('''# Exact V33 Form01 contact coverage observation

Compared the actual matched contact renders from this composition and the frozen neck-only candidate. The exposed structure gap between the distal neck and lower head hood remains visually about unchanged, with no obvious worsening. Orbital02 changes the head-owned throat seams above it. This is a visual observation, not proof of continuous protective coverage or physical attachment support.

All seven strict neck-neighbor surface-crossing counts are zero on exact native122076fb…; no pair is introduced versus V32 or the regional candidate. Zero crossings does not resolve the visible gap or grant full-fit, engineering or likeness acceptance. No geometry was changed by this check. The later jaw-bore-only Form02 is not covered by this receipt.
''')
files=[{'path':p.relative_to(OUT).as_posix(),'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(OUT.rglob('*')) if p.is_file()];assert all(sha(OUT/f['path'])==f['sha256'] for f in files);(OUT/'manifest.json').write_text(json.dumps({'status':receipt['status'],'native':receipt['native'],'compositionRegionSources':receipt['compositionRegionSources'],'relativePathHashesChecked':True,'files':files},indent=2)+'\n');print(json.dumps({'counts':[x['pairCount'] for x in screen['poses']],'nativeSHA256':sha(native),'receiptSHA256':sha(OUT/'receipt.json'),'manifestSHA256':sha(OUT/'manifest.json')}))
