from pathlib import Path
import json,hashlib,datetime
R=Path('/Users/okh/.codex/worktrees/cg-architect-cycle01/murderbird-uncaged');P=R/'assets/audit/cg-recursive-three-loop01/loop01'
def digest(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def get(n):return json.loads(Path('/tmp/cg-recursive-loop01-final-safety-'+n+'.json').read_text())
def claim(id,text,tier,evidence,consequence,next_check):return {'id':id,'claim':text,'tier':tier,'evidence':evidence,'consequence_if_false':consequence,'next_check':next_check}
n=get('native');s=get('static');ev=get('evaluated');maps=get('role-map');h=get('finish-readback')
rep={
 'schema_version':1,'role':'Independent SAFETY/PORTABILITY QA, final loop01 BODY01-only',
 'scope':'Exact frozen final199 resources, immutable09 receiving216 resources, read-only native/static GLB/build/source audit; artistic retention belongs to outcome/root.',
 'verdict':'PASS_WITH_LIMITS_FOR_DEVELOPMENT_CUSTODY',
 'answer':'No observed custody, licensing, private-output or runtime-promotion blocker in the actual frozen BODY01-only packet. It is mechanically usable as a retained development source if root outcome judgment selects it. Cross-host reproduction and successor receiving-manifest execution remain unproved.',
 'artifact_root':str(R),
 'freeze':{'manifest':str(P/'final-frozen-manifest.json'),'sha256':h['final199']['manifest_sha256'],'resources':199,'mismatches':h['final199']['mismatches'],'contract_sha256':digest(P/'final-review-contract.json'),'immutable09_manifest_sha256':h['immutable09_216']['manifest_sha256'],'immutable09_resources':216,'immutable09_mismatches':h['immutable09_216']['mismatches'],'last_complete_readback_utc':h['readback_time_utc']},
 'authority':{'read_files':['goal.md','assets/audit/cg-recursive-three-loop01/owner-authorization.json','assets/audit/cg-recursive-three-loop01/loop-control.json'],'goal_sha256':digest(R/'goal.md'),'latest_shared_goal_revision_recorded_in_control':'251f2f0243181e97140179c2aff6eb057e165438','revision_limit':'Read current goal bytes and recorded shared-main revision; did not fetch Git in this restricted QA task.','new_allowance':'Three loops, shared ten hours / one billion tokens / ten delegated agents, deadline 2026-10-05T00:20:42Z','owner_baseline':'09 useful more-than-incremental progress; target unmet; failed trial22 excluded','control_at_read':'active-owner-authorized; production_started true; loops_authorized 3; loops_completed 0','boundaries':'No main merge, runtime replacement, deploy, animation, engineering certification, purchase, dependency or paid Replit authorization.'},
 'actual_checks':[
  'Independent final199 + immutable09_216 complete SHA256 and byte-size readbacks, repeated after probes.',
  'Blender 5.2.1 background with autoexec disabled: independently fingerprinted each exact09 native and each matched02/retained02 native; no producer digest helper used.',
  'Compared original mesh coordinates, edges, loops, polygons, face material indices, smoothing, UV layers, supported generic attributes, shape keys, slots, world matrices, parents, custom properties, recorded modifier RNA, material-node inputs/links/properties and packed-image bytes within serialized fields.',
  'Compared recorded original camera/world/area-light/render settings, scene names and clay override absence; verified exact declared retirement visibility and new mesh era/role slots.',
  'Imported BODY01 and delivery02 with bytecode writes disabled; datablock inventories remained unchanged.',
  'Independent GLB JSON/BIN parser: valid chunks/buffer/accessor ranges, finite numeric attributes, position/normal/UV presence, valid triangle indices, embedded PNG metadata, no external URI, skins or animations.',
  'Independent native evaluated visible-mesh triangle counts by exact material name equal static GLB counts for all three eras.',
  'Every embedded GLB PNG matches a native packed image byte-for-byte; 57 same-era metal color/ORM/normal bindings per era match corresponding native material image bytes and dimensions.',
  'Verified Builder optic core emission factor [1,1,1] with strength5 and Maker/Mechanic nonemissive cores; all optic era tags match.',
  'Verified 23 actual PNGs per era in baseline and candidate, view-specific dimensions; compared paired camera/light/resolution/sample receipt fields, 12 samples in all views.',
  'Rehashed exact local dist52 file set against frozen build ledger; only unchanged V37 GLB, no audit/private/archive/provenance path leakage detected in emitted file names.',
  'Executed only extracted nonmutating actual runner02 path-guard AST against approved audit, public, private, frozen09, dist, other historical and invalid identifier cases.',
  'Read frozen browser record and actual capture pixels; read Advanced reset supplement separately outside freeze. No browser action or forced failure was performed by this reviewer.',
  'Visual sanity reads of pinned full-bird and retained Builder whole/head/body/profile/rear, Builder browser-neutral and Maker browser-exhibit pixels; source-scoped artistic score not assigned.'
 ],
 'native_results':n,
 'static_glb_summary':{e:{k:v for k,v in d.items() if k not in ('images','role_bindings','triangles_by_material')} for e,d in s['glbs'].items()},
 'native_to_glb_readback':{e:{'visible_native_meshes':d['visible_native_meshes'],'triangles':d['triangles'],'glb_native_material_triangle_counts_exact':d['glb_native_material_triangle_counts_exact'],'unmatched_glb_images':d['unmatched_glb_images'],'metal_materials':maps[e]['metal_materials'],'same_era_role_bindings_checked':maps[e]['role_bindings_checked'],'same_era_role_maps_exact':maps[e]['same_era_role_maps_exact']} for e,d in ev.items()},
 'render_pair_receipt_readback':h['render_receipt_pairs'],
 'dist_readback':s['dist'],'path_guard_probe':s['guards'],
 'material_claims':[
 claim('S01-C01','Original receiving payloads/material graphs/packed maps/stance transforms/recorded rig remain preserved in all three native successors, except exactly34 declared hides;36 meshes intentionally added.','confirmed', ['/tmp/cg-recursive-loop01-final-safety-native.json','/tmp/cg-recursive-loop01-final-safety-native.py'],'A claimed successor could silently replace inherited source identity or pose.','Repeat scoped fingerprints if any native/source/module bytes change.'),
 claim('S01-C02','Current static GLBs embed exact native map bytes with same-era metal map roles; finite indexed triangles and aggregate material face counts match native evaluated output.','confirmed',['/tmp/cg-recursive-loop01-final-safety-static.json','/tmp/cg-recursive-loop01-final-safety-evaluated.json','/tmp/cg-recursive-loop01-final-safety-role-map.json'],'Browser appearance could derive from missing maps, wrong era roles or dropped geometry.','Full per-triangle corner correspondence and rendered shader/light parity were not independently tested; do not claim those.'),
 claim('S01-C03','Three native successors,69 candidate and69 baseline PNGs,3 static embedded GLBs are present; matched metadata and source-preservation proof support a development packet.','confirmed',['final-frozen-manifest.json','/tmp/cg-recursive-loop01-final-safety-finish-readback.json','/tmp/cg-recursive-loop01-final-safety-static.json'],'Incomplete or mismatched evidence might be mistaken for a complete comparison.','Outcome QA/root decide visible whole-character gain, independently of technical checks.'),
 claim('S01-C04','All three eras were rendered in actual IAB with both lights and manual PNG fallback, with recorded reset actions only.','source-reported plus capture-pixel observed',['browser-verification.json','browser-captures/','supplements/advanced-reset.json'],'Screenshots or stale state could be upgraded to unperformed browser behavior.','No independent action replay by this reviewer; orbit, zoom, forced failure, mobile/performance remain not run.'),
 claim('S01-C05','Local dist matches52 frozen listed files and contains only the existing V37 runtimeGLB.','confirmed',['local-build-inspection.json','/tmp/cg-recursive-loop01-final-safety-static.json'],'Development model or private/audit material could be included in release output.','A future runtime edit needs a fresh exact build inspection and separate publication evidence.'),
 claim('S01-C06','BODY01/delivery02 inert imports and dynamic required runner source-root support a controlled local production contract; cross-host portability is not established.','confirmed within import/static fields; portability unknown',['scripts/cg-recursive-body01.py','scripts/cg-recursive-delivery02.py','/tmp/cg-recursive-loop01-final-safety-native.json'],'Host defaults, paths or retained-manifest assumptions could fail during continuation elsewhere.','Use exact new audit output, explicit source-root and complete retained custody counts; test successor mode when it is actually authorized/used.'),
 claim('S01-C07','Creative materials remain all rights reserved; code is MIT. Source references and original09 history remain unchanged.','confirmed repository policy and hashed files',['NOTICE.md','docs/repository-boundaries.md','assets/README.md','/tmp/cg-recursive-loop01-final-safety-finish-readback.json'],'Public reuse rights or publication approval could be overstated.','Maintain private/archive and explicit runtime reference boundaries in any later publication.'),
 claim('S01-C08','Photoreal source-twin completion, owner acceptance and meaningful artistic retention are not established by this safety QA.','unknown/not adjudicated',['final-review-contract.json','owner-authorization.json'],'Technical acceptance could erase the source likeness hard gate.','Independent outcome/root whole-character judgment and eventual owner acceptance remain necessary.')
 ],
 'usable_limits':[
  'Actual outputs use approved new loop01 audit checkpoint paths. No native source/model/application edit by this reviewer.',
  'All three retained natives have7644 mesh+empty payloads,62 original material graphs; packed FILE image counts161 Builder and160 Maker/Mechanic. Matched02 originals7608. Receiving09 resources remain byte-exact.',
  'GLBs are static world-space material batches,24 meshes/24 primitives,619602 triangles each;0 skins/animations. This does not establish a production rig or mechanics.',
  'Native packed maps are self-contained for material readback although historical image filepaths and some provenance receipt paths are absolute host paths. Standalone generation and other-host regeneration require explicit root/path support.',
  'Matched wholes/profile/turntables1280x853,three detail views1280x1280,hero960x1280; all69 pairs report matching camera/light fields and12samples.',
  'Browser/native lighting differences are declared. Screenshot tone differs from native renders; no pixel/shader parity is claimed.',
  'Current browser records describe initial triangles12 as possible first-frame environment pre-render timing; actual reset readback619602 agrees with independently counted GLBs. This is not missing-model proof.',
  'Frozen browser report had separate Advanced reset pending. Additional Advanced reset action/state is recorded in supplement outside199; the supplement resolves the stated pending control evidence only, does not change judged models/frozen bytes, and was not independently replayed here.',
  'No obvious missing limb or new stance regression in sanity pixels. Puffy breast plates/dark gap/upper join costs remain visible considerations for outcome reviewers; inherited head simplification remains visible. Those observations do not constitute an artistic acceptance verdict.'
 ],
 'necessary_corrections':[
  {'priority':'before claiming general output safety','issue':'Runner02 comment says every frozen asset/audit directory is protected, but actual guards reject only public/.local and two cg-supervised01 trees. Dist and other historical paths pass the extracted guard.','actual_packet_effect':'None observed; approved new loop01 output path passes and all protected hashes stay exact.','correction':'Keep all current/future invocations in explicitly approved new audit paths. Broaden the guard or narrow its all-historical wording before claiming universal protection. Existing checkpoint collision and exact unfinalized signature rules remain narrower local safeguards.'},
  {'priority':'before successor-mode portability claim','issue':'Retained receiving-manifest mode is static only in this freeze. It requires root approval,loop2/3, native SHA and a custody-count dictionary, but compares only supplied dictionary keys; it does not enforce a complete field schema.','actual_packet_effect':'None for current exact09 path; runner02 actual three-era receiving counts pass.','correction':'Construct a complete explicit custody inventory for each retained native and hash-pin it. Do not treat an empty/partial count dictionary as full custody proof. Execute/review successor mode when used; no execution claimed here.'},
  {'priority':'before standalone/body cross-host production','issue':'BODY01 standalone runner keeps an absolute default ROOT and creates/reuses fixed attempt paths. Its apply() draws era-role materials from the loaded scene without independently rejecting a mismatched era tag.','actual_packet_effect':'None observed in actual delivery02 calls; all new slot roles and era maps are independently correct and imports inert.','correction':'Continue using hash-pinned delivery02 with required explicit source-root,versioned new checkpoint and verified loaded-era scene. Do not claim arbitrary standalone invocations are portable/collision-safe.'}
 ],
 'browser_supplement':{'path':str(P/'supplements/advanced-reset.json'),'sha256':digest(P/'supplements/advanced-reset.json'),'in_final199':False,'actual_action_reported':'Advanced reset3Dview click','triangles_reported':619602,'independently_replayed':False},
 'not_run':[
  'Model apply, editing, render, save, new export, browser automation, dependency install, Git operation, upload, purchase or publication by this reviewer.',
  'Full per-triangle corner identity across native-toGLB, new shader/light pixel-parity test, calibrated source-camera/depth validation.',
  'Retained receiving-manifest mode production execution; other-host/clean-checkout reproduction and remote LFS retrieval.',
  'Manual browser orbit/zoom,forced WebGL failure path, mobile/device/performance/accessibility coverage; manual PNG fallback does not prove forced failure.',
  'Remote CI/deployment/public runtime integration or owner artistic acceptance.',
  'Rig/animation,manifold/engineering/mechanical fabrication or physical validation.'
 ],
 'independence_limits':[
  'Same shared Sol model family, repository, Blender semantics and development-seen sources; no protected holdout or cross-family blinded review.',
  'This QA reuses its own prior visual and initial safety context and helper fingerprint functions, but reran full current frozen native/GLB/dist readbacks. Earlier combined HEAD+BODY and runner01 limits are historical and are not attributed to current BODY-only runner02 as unresolved era-count failures.',
  'No other current QA output/report was read; producer receipts, frozen contract/browser record and parent control messages were read.',
  'Image sanity subset only; artistic ranking/retention delegated to independent outcome/root. All reference images were development-seen.',
  'Serialized native comparison covers recorded fields rather than every Blender property. Material triangle parity is aggregate by material, not independently proven per-face GLB correspondence.',
  'Browser actions and npm build commands were producer/root reported; this reviewer inspected their actual capture pixels, embedded binaries and emitted file hashes without rerunning them.'
 ],
 'own_probe_artifacts':[{ 'path':str(p),'sha256':digest(p)} for p in [Path('/tmp/cg-recursive-loop01-final-safety-native.py'),Path('/tmp/cg-recursive-loop01-final-safety-native.json'),Path('/tmp/cg-recursive-loop01-final-safety-static.py'),Path('/tmp/cg-recursive-loop01-final-safety-static.json'),Path('/tmp/cg-recursive-loop01-final-safety-evaluated.py'),Path('/tmp/cg-recursive-loop01-final-safety-evaluated.json'),Path('/tmp/cg-recursive-loop01-final-safety-role-map.json'),Path('/tmp/cg-recursive-loop01-final-safety-finish-readback.json')]],
 'hard_stop_utc':'2026-10-04T16:40:00Z','finished_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()
}
Path('/tmp/cg-recursive-loop01-final-safety.json').write_text(json.dumps(rep,indent=2)+'\n');print(json.dumps({'path':'/tmp/cg-recursive-loop01-final-safety.json','sha256':digest('/tmp/cg-recursive-loop01-final-safety.json'),'verdict':rep['verdict'],'finished_utc':rep['finished_utc'],'bytes':Path('/tmp/cg-recursive-loop01-final-safety.json').stat().st_size}))
