import bpy,json,hashlib,importlib.util,sys
sys.dont_write_bytecode=True
from pathlib import Path
from mathutils import Vector
p=Path('/Users/okh/.codex/worktrees/cg-supervised-oblique-breast15/murderbird-uncaged/assets/audit/cg-recursive-body03-gap/attempt01');native=p.parents[2]/'models/cg-recursive-body03-gap/attempt01/murderbird-body03-gap-builder.blend'
beforeImport=(len(bpy.data.objects),len(bpy.data.materials),len(bpy.data.images));sp=importlib.util.spec_from_file_location('body03_api','/Users/okh/.codex/worktrees/cg-supervised-oblique-breast15/murderbird-uncaged/scripts/cg-recursive-body03-gap.py');api=importlib.util.module_from_spec(sp);sp.loader.exec_module(api);assert beforeImport==(len(bpy.data.objects),len(bpy.data.materials),len(bpy.data.images))
for era in ('builder','maker','mechanic'):
 native=Path('/Users/okh/.codex/worktrees/cg-supervised-oblique-breast15/murderbird-uncaged/assets/models/cg-recursive-body03-gap/attempt01')/('murderbird-body03-gap-'+era+'.blend')
 r=json.loads((p/era/'receipt.json').read_text());bpy.ops.wm.open_mainfile(filepath=str(native));s=bpy.context.scene
 rig={o.name:dict(location=list(o.location),rotation=list(o.rotation_euler),scale=list(o.scale),data=dict(type=o.data.type,ortho_scale=o.data.ortho_scale,lens=o.data.lens,shift_x=o.data.shift_x,shift_y=o.data.shift_y) if o.type=='CAMERA' else dict(energy=o.data.energy,color=list(o.data.color),size=o.data.size)) for o in s.objects if o.type in ('CAMERA','LIGHT')};assert rig==r['originalRig'];b=s.world.node_tree.nodes.get('Background');assert [list(b.inputs[0].default_value),b.inputs[1].default_value]==r['originalWorld'];assert len(bpy.data.materials)==62
 q=r['cameras']['candidate-neutral-000-pbr'];c=s.camera;c.location=q['location'];c.rotation_euler=q['rotation_euler'];c.data.type=q['projection'];c.data.ortho_scale=q['ortho_scale'];c.data.shift_x,c.data.shift_y=q['shift'];bpy.context.view_layer.update();rot=c.matrix_world.to_quaternion();f=rot@Vector((0,0,-1));rr=rot@Vector((1,0,0));up=rot@Vector((0,1,0));w,h=1280,853
 old=json.loads((p/'cg-body03-gap-inspection.json').read_text())['views']['neutral-000']['connectedGapComponents'][0]['rearHitSamples'];hits=[]
 for v in old:
  x,y=v['xNormalized'],v['yNormalized'];origin=c.location+rr*((x-.5)*c.data.ortho_scale)+up*((.5-y)*c.data.ortho_scale*h/w);hit,loc,n,idx,o,m=s.ray_cast(bpy.context.evaluated_depsgraph_get(),origin,f,distance=30);hits.append(dict(pixel=v['pixel'],object=o.name if hit else None,anterior=bool(hit and loc.y<-.25)))
 result=dict(importInert=True,era=era,newMeshCount=sum(bool(o.get('cgRecursiveBody03Gap')) for o in s.objects),meshEmptyCount=sum(o.type in ('MESH','EMPTY') for o in s.objects),packedImageCount=sum(bool(i.packed_file) for i in bpy.data.images),newGeometry={o.name:hashlib.sha256(repr(([tuple(v.co) for v in o.data.vertices],[tuple(p.vertices) for p in o.data.polygons])).encode()).hexdigest() for o in s.objects if o.get('cgRecursiveBody03Gap')},originalRigExact=True,originalWorldExact=True,materialCount=62,all112FormerMainGapSamplesAnterior=all(v['anterior'] for v in hits),hits=hits);assert len(hits)==112 and result['all112FormerMainGapSamplesAnterior'];(p/era/'supplemental-custody.json').write_text(json.dumps(result,indent=2)+'\n');print('SUPPLEMENTAL_BODY03',len(hits),len(bpy.data.materials),rig==r['originalRig'])
