from pathlib import Path
import bpy,json,hashlib
from mathutils import Vector
R=Path('/Users/okh/.codex/worktrees/review-regression/murderbird-uncaged');A=Path(__file__).parent;N=R/'assets/models/whole-character-v35/regional-studies/torso-integration/attempt05/murderbird-torso-integration.blend'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();S='2589ea9bef35caa5b65cbae3edddec856422f8f4729df0e8ec38b373d2136857';assert sha(N)==S
screen=json.loads((A/'screen.json').read_text());base={tuple(sorted((r['meshA'],r['meshB']))) for r in screen['base']['poses'][0]['pairs']};rows=[r for r in screen['candidate']['poses'][0]['pairs'] if tuple(sorted((r['meshA'],r['meshB']))) not in base];assert len(rows)==6
bpy.ops.wm.open_mainfile(filepath=str(N));bpy.context.view_layer.update();dg=bpy.context.evaluated_depsgraph_get()
scene=bpy.context.scene;scene.render.engine='BLENDER_WORKBENCH';s=scene.display.shading;s.light='STUDIO';s.studio_light='paint.sl';s.color_type='OBJECT';s.show_shadows=False;s.show_cavity=True;s.cavity_type='BOTH';s.background_type='WORLD';scene.world.color=(.12,.13,.14);scene.render.resolution_x=scene.render.resolution_y=700;scene.render.resolution_percentage=100;scene.render.image_settings.file_format='PNG'
d=bpy.data.cameras.new('temporary pair diagnostic');d.type='ORTHO';d.ortho_scale=.18;cam=bpy.data.objects.new(d.name,d);scene.collection.objects.link(cam);scene.camera=cam
for i,row in enumerate(rows,1):
 names=[row['meshA'],row['meshB']];bounds=[]
 for o in bpy.data.objects:
  if o.type in ['MESH','CURVE']:o.hide_render=o.name not in names
 for k,name in enumerate(names):
  o=bpy.data.objects[name];assert o.parent.name=='body';o.color=(.38,.53,.67,1) if k==0 else (.73,.59,.39,1);ev=o.evaluated_get(dg);m=ev.to_mesh();v=[ev.matrix_world@p.co for p in m.vertices];bounds.append([[min(p[j] for p in v),max(p[j] for p in v)] for j in range(3)]);ev.to_mesh_clear()
 target=Vector(row['firstWitness']['combinedCentroidWorld']);side=1 if target.x>0 else -1;cam.location=target+Vector((side*.8,-.4,.26));cam.rotation_euler=(target-cam.location).to_track_quat('-Z','Y').to_euler();scene.render.filepath=str(A/f'fixed-junction-{i:02d}.png');bpy.ops.render.render(write_still=True)
 rib=names[0].startswith('V23 thoracic formed rib');role='Matched C-section end cope into retained rib; proposed fixed welded receiver seam' if rib else ('Posterior C-stiffener tied into retained rising shoulder cheek; proposed fixed welded crossmember seam' if 'receiving cheek' in names[0] else 'Posterior C-stiffener tied into retained shoulder lower load fork; proposed fixed welded crossmember seam')
 row.update({'disposition':role,'classification':'Introduced actual same-body solid crossing at individually declared fixed joined-frame seam; not independently moving clearance, not suppressed in strict screen','constructionBasis':'Both actual meshes are single body-owned passive structural members. New rail remains a substantial connected closed positive solid; selected end/junction ties it to retained shoulder-to-rib load path. Welding is a construction proposal, not qualified fabrication or stress validation. Separate source meshes are retained rather than claiming a Boolean-unioned shared topology.','evaluatedWorldBounds':dict(zip(names,bounds)),'AABBOverlapWorld':[[max(bounds[0][j][0],bounds[1][j][0]),min(bounds[0][j][1],bounds[1][j][1])] for j in range(3)],'image':f'fixed-junction-{i:02d}.png','imageSHA256':sha(Path(scene.render.filepath)),'imageMethod':'Read-only diagnostic isolation of two actual solids, temporary object colors distinguish retained receiver/new rail; does not show whole-character visibility. Native not saved.'})
(A/'fixed-junction-disposition.json').write_text(json.dumps({'nativeSHA256':S,'moduleSHA256':sha(A/'executed-torso-integration.py'),'executedReviewSHA256':sha(Path(__file__)),'screenSHA256':sha(A/'screen.json'),'headline':'Six introduced fixed joined-frame solid crossings remain explicitly reported; no moving interowner crossings at seven sampled states. Proposed receiving/weld seams, not a blanket clearance pass.','pairs':rows,'nativeUnchanged':sha(N)==S},indent=2)+'\n');assert sha(N)==S
