"""Assemble a local-only review document; never edits/warps source imagery."""
from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'assets/audit/neutral-v2'
inv=json.loads((ROOT/'assets/models/uncaged-neutral-v2/neutral-inventory.json').read_text());model=next(f for f in inv['generatedFiles'] if f['path'].endswith('.glb'))
def fig(src,label):return f'<figure><a href="{src}"><img loading="lazy" src="{src}" alt="{escape(label)}"></a><figcaption>{escape(label)}</figcaption></figure>'
parts=['''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MurderBird — Neutral correction v2</title><style>body{font:17px/1.55 system-ui;background:#e9e8e3;color:#202522;margin:0}main{max-width:1500px;margin:auto;padding:30px}h1{font-size:2.2rem;line-height:1.15}h2{margin-top:44px}.note{background:#fff3cf;padding:18px;border-left:5px solid #8b6028}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.two{grid-template-columns:repeat(2,minmax(0,1fr))}figure{margin:0;background:#f8f7f3;padding:12px}img{width:100%;height:520px;object-fit:contain}figcaption{font-size:14px}a{color:#244e60}code{overflow-wrap:anywhere}video{max-width:100%;width:1100px;background:#000}table{border-collapse:collapse;width:100%}td,th{text-align:left;vertical-align:top;padding:10px;border-bottom:1px solid #b7bbb6}nav{display:flex;gap:20px;flex-wrap:wrap}@media(max-width:800px){main{padding:16px}.grid,.two{grid-template-columns:1fr}img{height:auto}h1{font-size:1.7rem}}</style><main><nav><a href="../../../">Local interactive exhibit</a><a href="../../../docs/correction-v2-stage-b-review.md">Supervisor assessment</a><a href="../../../docs/correction-v2-backlog.md">F01–F10 backlog</a><a href="../../../docs/correction-v2-reference-packet.md">Reference decisions</a><a href="../../../docs/correction-v2-neutral-independent-review.md">Independent observations</a></nav><h1>Neutral correction v2<br>Shape before finish.</h1><p class="note"><strong>Stage B review — revision remains required.</strong> This is a new neutral structure proposal in the local application, not a published release or a finished three-era exterior. The prior inspector scores belong to the historical model. No new full score or owner acceptance is claimed.</p>''']
parts.append(f'<p>Model <code>{model["sha256"]}</code> · {model["bytes"]:,} bytes. <a href="../../models/uncaged-neutral-v2/murderbird-neutral-v2.blend">Editable Blender source</a> · <a href="../../models/uncaged-neutral-v2/murderbird-neutral-v2.glb">Runtime GLB</a> · <a href="../../models/uncaged-neutral-v2/neutral-inventory.json">Parts, pivots and hashes</a>.</p>')
parts.append('<p>The body tapers lower down, the curved neck is broader, the mantle wraps the shoulder/elbow, and each toe has separate hinges. Crown/cheek identity, fine leg construction and moving clearance remain review questions. Rear and hidden machinery are reconstructions. Neutral maps and authored dimensions are not recovered historical measurements.</p>')
refs={'maker':('I · Maker','murderbird-unified-maker-clean-candidate-2026-09-06.png'),'mechanic':('II · Mechanic','murderbird-unified-mechanic-candidate-2026-09-06.png'),'builder':('III · Advanced','murderbird-unified-master-candidate-03-2026-09-06.png')}
for era,(title,ref) in refs.items():
 parts.append(f'<h2>{title} · whole-body comparison</h2><p>Source is complete and uncropped. Model camera approximates its perspective and direction; lens and pose uncertainty remain. No warped geometry, numerical similarity score or exact dimension claim.</p><div class="grid">')
 parts.extend([fig('../../img/library/'+ref,title+' controlling appearance illustration'),fig('baseline/'+era+'-reference-perspective.png','Inspected exterior v1 · same authoring camera as new candidate'),fig(era+'-reference-perspective.png','Neutral v2 · proposed body/neck/mantle/limbs')]);parts.append('</div>')
parts.append('<h2>Head-only authority</h2><p>The July image controls the head. Its body, perch and hanging wing train are excluded. The complete original remains available beside the model close-up.</p><div class="grid two">')
parts.append(fig('../../../context/threads/assets/murderbird-camera-series-2026-09-05/murderbird-owner-preferred-july-reference.png','July owner-preferred image · head scope only'))
parts.append(fig('neutral-head.png','New crown / optic / hooked bill / separate jaw · neutral reconstruction'));parts.append('</div>')
parts.append('<h2>Before / after at fixed cameras</h2><p>The model renders use the same view, framing and projection. Solid preview material values differ between versions; this is a qualitative shape comparison. Perspective reference art is not an orthographic drawing.</p>')
for name in ['front','side-right','rear','three-quarter']:
 parts.append('<div class="grid two">'+fig('baseline/neutral-'+name+'.png','Exterior v1 · '+name)+fig('neutral-'+name+'.png','Neutral v2 · '+name)+'</div>')
parts.append('<h2>Reconstructed views and details</h2><div class="grid">')
for name in ['side-left','left-three-quarter','elevated','low','feet','mantle','breast']:parts.append(fig('neutral-'+name+'.png','Neutral v2 · '+name))
parts.append('</div><h2>Actual browser and joint extrema</h2><p>These captures show the local WebGL export and runtime mechanisms. They are separate from authoring renders. Individual samples do not prove every swept collision or real physical balance.</p><div class="grid">')
for era in refs:
 for name in ['exterior-neutral','head-closeup','neck-closeup','shoulder-closeup','feet-closeup','inspection-open','inspection-exploded']:
  p=OUT/(era+'-'+name+'.png')
  if p.exists():parts.append(fig(p.name,refs[era][0]+' · actual browser '+name))
for p in sorted(OUT.glob('*extreme.png')):parts.append(fig(p.name,'Actual browser · '+p.stem))
parts.append('</div><h2>Frozen live poses, both sides</h2><p>The existing pause control holds the live phase while the camera orbits. Jaw views are centered on the actual head. Contact is kinematic; this is not force or swept-collision certification. <a href="frozen-extrema.json">Phase and attachment receipt</a>.</p><div class="grid">')
for p in sorted(OUT.glob('*-frozen-*.png')):parts.append(fig(p.name,'Paused live pose · '+p.stem))
parts.append('</div>')
if (OUT/'neutral-motion-demonstration.mp4').exists():parts.append('<h2>Silent movement envelope</h2><p>Uncut local browser sequence. The visible clock and logged samples share one performance clock; setup precedes its zero marker. This is a kinematic demonstration, not physics or final acting approval.</p><video controls preload="metadata" src="neutral-motion-demonstration.mp4"></video><p><a href="motion-demonstration.json">Synchronized event/sample receipt</a></p>')
parts.append('<h2>Two source decisions</h2><p><strong>V10:</strong> recommended interpretation: the original twice-fitted left plate causes the restricted fit; the Mechanic adds a separate load-bearing strap, and Advanced retains both. The alternative lets the later brace add a secondary stop. Exact geometry remains proposed.</p>')
parts.append(fig('decisions/left-shoulder-chronology-options.svg','Left shoulder chronology · proposed attachment diagram'))
parts.append('<p><strong>V12:</strong> recommended interim scope: preserve the historical Maker/Mechanic clips as context, while reviewing the owner-directed external-control and limited-step reconstructions on their own merits. No controlling early-era motion clip is currently approved. See the <a href="../../../docs/correction-v2-reference-packet.md">timecode ledger and options</a>.</p>')
parts.append('<h2>Acceptance boundary</h2><p>Maker: neutral structural proposal, not a visual twin. Mechanic: neutral structural proposal, repair chronology pending. Advanced: neutral structural proposal with remaining facial/limb and acting gaps. Material history, a purposeful articulated claw action, complete human/device reviews and full rescoring remain outstanding. Technical passes do not approve any era.</p><p>Nothing in this local review authorizes publication. The old public exhibit/review remains historical baseline evidence.</p><footer>© Jamie Hill / OverKill Hill P³ · Creative content all rights reserved.</footer></main></html>')
(OUT/'neutral-review.html').write_text('\n'.join(parts)+'\n')
print(OUT/'neutral-review.html')
