"""Assemble the local review gallery from actual captured evidence."""
from pathlib import Path
import json,html,hashlib
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'assets/audit/exterior-v1'
model=ROOT/'assets/models/uncaged-exterior-v1/murderbird-exterior-v1.glb'
model_sha=hashlib.sha256(model.read_bytes()).hexdigest()
def fig(src,title,caption=''):
 return f'<figure><a href="{src}" target="_blank"><img loading="lazy" src="{src}" alt="{html.escape(title)}"></a><figcaption><b>{html.escape(title)}</b>{html.escape(caption)}</figcaption></figure>'
refs={'maker':'murderbird-unified-maker-clean-candidate-2026-09-06.png','mechanic':'murderbird-unified-mechanic-candidate-2026-09-06.png','builder':'murderbird-unified-master-candidate-03-2026-09-06.png'}
labels={'maker':'I · Maker','mechanic':'II · Mechanic','builder':'III · Advanced'}
parts=[]
for era in refs:
 parts.append(f'<section id="{era}"><h2>{labels[era]}</h2><p>'+{'maker':'Newly fabricated, before immersion. Individual formed plates, passive bearings and dark optic recesses. External controls remain visible.','mechanic':'The inherited shell after aging and repair. Iron braces and replacement strips retain visible edges and different fasteners. The optic remains unlit.','builder':'The aged body and repair landmarks remain. Protected upgrades, separate power and processing, and a restrained amber lens carry the new capability.'}[era]+'</p><div class="pair">')
 parts.append(fig('../../img/library/'+refs[era],'Selected era reference','Perspective illustration; exact hidden construction is not established.'))
 parts.append(fig(era+('-reference-angle.png' if era!='builder' else '-authoring-neutral.png'),labels[era]+' · neutral source-comparison angle','Proposed geometry, viewed from the same side as the selected illustration; perspective is not an exact dimensional match.'))
 parts.append('</div><div class="gallery">')
 for p in sorted(list(OUT.glob(era+'-*.png'))+(list(OUT.glob('advanced-*.png')) if era=='builder' else [])):
  if 'authoring' in p.name or 'reference-angle' in p.name:continue
  parts.append(fig(p.name,p.stem.replace(era+'-','').replace('-',' '),'Browser capture of this local build.'))
 parts.append('</div></section>')
views=[]
for v in ['three-quarter','front','side','rear','head']:
 views.append(f'<h3>{v.replace("-"," ").title()}</h3><div class="pair">'+fig('../structural-reconciliation-v1/after-'+v+'.png','Structural v1 · before','Same orthographic camera and scale.')+fig('exterior-clay-'+v+'.png','Exterior v1 · geometry','Neutral clay isolates silhouette and construction.')+'</div>')
iteration_views=[]
for image_name in ['builder-authoring-neutral.png','exterior-clay-side.png']:
 iteration_views.append('<div class="pair">'+fig('../../models/uncaged-exterior-v1/iterations/iteration-a/'+image_name,'Earlier exterior iteration A','Preserved before the final geometry correction; not the current runtime.')+fig(image_name,'Current exterior review','Same authoring camera and lighting for this pair.')+'</div>')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MurderBird — Three exteriors v1</title><style>
*{box-sizing:border-box}body{margin:0;background:#141916;color:#ebece4;font:16px/1.6 system-ui,sans-serif}main{max-width:1480px;margin:auto;padding:40px 24px}h1{font-size:clamp(32px,4.5vw,64px);line-height:1.08;max-width:17ch}h2{font-size:32px;margin:56px 0 8px}h3{text-transform:capitalize}p{max-width:90ch;color:#c4c9bd}a{color:#dfbc7f}nav{display:flex;gap:24px;flex-wrap:wrap}figure{margin:0;border:1px solid #4a5046;background:#222a24;min-width:0}figure img{width:100%;display:block}figcaption{padding:16px;color:#b9c2b5}figcaption b{display:block;color:#f0eadc}.pair,.gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin:20px 0}.gallery{grid-template-columns:repeat(3,minmax(0,1fr))}.note{border-left:3px solid #d4b077;background:#232b24;padding:16px 22px}.tag{text-transform:uppercase;letter-spacing:.16em;color:#cca876;font:12px monospace}video{width:100%;max-height:820px;background:#080b09}summary{cursor:pointer;color:#dfbc7f;font-size:24px;margin-top:45px}.headcrop{aspect-ratio:510/450;position:relative;overflow:hidden;max-width:430px}.headcrop img{position:absolute;width:200.784%;max-width:none;left:-98.039%;top:-4.444%}@media(max-width:750px){main{padding:24px 14px}.pair,.gallery{grid-template-columns:1fr}}
</style><main><span class="tag">Local production · exterior v1</span><h1>One bird.<br>Three histories.</h1><p class="note"><b>Implemented exterior proposal · artistic review pending.</b> These are three construction states of the same inherited bird. Geometry, surface response and movement have been reviewed together. The broader folded mantle, crown/bill, plate rhythm and leg detail still need likeness work. This package does not yet meet the full artistic acceptance criteria. New seams, hidden surfaces and repairs remain interpretations.</p><nav><a href="/">Open local exhibit</a><a href="#maker">Maker</a><a href="#mechanic">Mechanic</a><a href="#builder">Advanced</a><a href="#motion">Motion</a><a href="#silhouette">Geometry changes</a></nav>
<p>Neutral source-comparison renders use the corresponding side of the bird. Browser captures use consistent bird-relative cameras, neutral and intended exhibit light, close-ups and inspection. Reference images use perspective; front, rear and hidden construction are reconstructions.</p>
'''+''.join(parts)+'''<details><summary>July head reference · selected head only</summary><div class="headcrop"><img src="../../../context/threads/assets/murderbird-camera-series-2026-09-05/murderbird-owner-preferred-july-reference.png" alt="Owner-selected July head reference"></div><p>The constructed bill, cheek opening, optic housing and swept crown control the head. Its body, long hanging wings and support are outside the selection.</p></details>
<h2 id="motion">Appearance in motion</h2><p>The continuous capture includes Maker's five controls, Mechanic's stepped movement and turns, and Advanced pacing, jump, shield thrust, strike and recovery. Inspection and reassembly are exercised in each era. These are kinematic exhibit reconstructions.</p><video controls preload="metadata" src="exterior-motion-demonstration.mp4"></video>
<details id="silhouette"><summary>Before and after · matched geometry views</summary>'''+''.join(views)+'''</details>
<h2>Construction and evidence</h2><nav><a href="../../../docs/exterior-stage-record.md">Review and remaining decisions</a><a href="../../../docs/exterior-regional-map.md">Regional construction and attachments</a><a href="../../../docs/exterior-surface-pipeline.md">Surface pipeline</a><a href="../../../assets/models/uncaged-exterior-v1/exterior-inventory.json">Component inheritance</a><a href="browser-validation.json">Browser and performance evidence</a><a href="asset-validation.json">Export and build evidence</a></nav><p>All MurderBird creative material is all rights reserved under NOTICE.md. Local review only; this is distinct from the deployed website.</p></main></html>'''
page=page.replace('<h2 id="motion">', '<details><summary>Exterior correction · preserved iteration comparison</summary>'+''.join(iteration_views)+'</details><h2 id="motion">')
page=page.replace('<h2>Construction and evidence</h2>', '<h2>Construction and evidence</h2><p>Exact local runtime SHA-256: <code style="overflow-wrap:anywhere">'+model_sha+'</code>. <a href="../../models/uncaged-exterior-v1/murderbird-exterior-v1.blend">Editable source</a> · <a href="../../models/uncaged-exterior-v1/README.md">Versioned model package</a>.</p>')
(OUT/'exterior-review.html').write_text(page)
print('EXTERIOR_REVIEW',OUT/'exterior-review.html')
