#!/usr/bin/env python3
"""Publish only the manifest-pinned exterior review media and a rewritten gallery.

Run after the Vite build. --check verifies an existing derivative without changing
it. GITHUB_SHA selects immutable repository links; otherwise git HEAD is used.
The checked-in manifest is deliberately not regenerated by this release tool.
"""
import argparse
import hashlib
import html
from html.parser import HTMLParser
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import subprocess
from urllib.parse import quote, unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'assets/review/exterior-v1-publication.json'
REPOSITORY = 'https://github.com/OKHP3/murderbird-uncaged'
POINTER = b'version https://git-lfs.github.com/spec/v1'


def require(condition, message):
    if not condition:
        raise ValueError(message)


def local_file(relative):
    require(not Path(relative).is_absolute(), f'Absolute source path: {relative}')
    path = (ROOT / relative).resolve()
    require(path.is_relative_to(ROOT) and path.is_file(), f'Invalid source: {relative}')
    return path


def verified_bytes(entry):
    data = local_file(entry['source']).read_bytes()
    require(not data.startswith(POINTER), f'Unhydrated LFS source: {entry["source"]}')
    require(len(data) == entry['bytes'], f'Source size mismatch: {entry["source"]}')
    require(hashlib.sha256(data).hexdigest() == entry['sha256'],
            f'Source hash mismatch: {entry["source"]}')
    return data


class References(HTMLParser):
    def __init__(self, source):
        super().__init__(convert_charrefs=True)
        self.links = []
        self.media = []
        self.ids = set()
        self.feed(source)

    def handle_starttag(self, tag, attributes):
        attrs = dict(attributes)
        if attrs.get('id'):
            self.ids.add(attrs['id'])
        for name in ('src', 'href', 'poster'):
            if attrs.get(name):
                self.links.append((tag, name, attrs[name]))
        if tag in ('img', 'video', 'source') and attrs.get('src'):
            self.media.append(attrs['src'])


def source_path(gallery, url):
    parts = urlsplit(url)
    require(not parts.scheme and not parts.netloc and not parts.query,
            f'Unexpected source URL: {url}')
    path = (gallery.parent / unquote(parts.path)).resolve()
    require(path.is_relative_to(ROOT) and path.is_file(), f'Unresolved source link: {url}')
    return path.relative_to(ROOT).as_posix()


def revision():
    requested = os.environ.get('GITHUB_SHA') or subprocess.check_output(
        ['git', 'rev-parse', 'HEAD'], cwd=ROOT, text=True).strip()
    require(re.fullmatch(r'[a-fA-F0-9]{40}', requested), 'Build revision must be a full Git SHA')
    resolved = subprocess.check_output(
        ['git', 'rev-parse', '--verify', requested + '^{commit}'], cwd=ROOT, text=True).strip()
    require(resolved == requested.lower(), 'Build revision did not resolve exactly')
    return resolved


def load_inputs():
    manifest = json.loads(MANIFEST.read_text())
    require(manifest['schemaVersion'] == 1, 'Unsupported publication manifest')
    require(manifest['repository'] == REPOSITORY, 'Unexpected repository')
    gallery = local_file(manifest['gallery']['source'])
    source = verified_bytes(manifest['gallery']).decode('utf-8')
    verified_bytes(manifest['model'])
    media = manifest['media']
    require(len({entry['source'] for entry in media}) == len(media), 'Duplicate manifest source')
    require(len({entry['output'] for entry in media}) == len(media), 'Duplicate manifest output')
    referenced = {source_path(gallery, url) for url in References(source).media}
    require(referenced == {entry['source'] for entry in media},
            'Manifest must exactly match referenced image/video sources')
    for entry in media:
        output = PurePosixPath(entry['output'])
        require(output.parts[:2] == ('review', 'media') and len(output.parts) == 3,
                f'Output is outside review/media: {output}')
        require(output.suffix in ('.png', '.mp4'), f'Unsupported review media: {output}')
        require(local_file(entry['source']).suffix == output.suffix,
                f'Media extension mismatch: {output}')
        data = verified_bytes(entry)
        if output.suffix == '.png':
            require(data.startswith(b'\x89PNG\r\n\x1a\n'), f'Invalid PNG: {output}')
        else:
            require(data[4:8] == b'ftyp', f'Invalid MP4: {output}')
    return manifest, gallery, source


def render(manifest, gallery, source, sha):
    mapped = {entry['source']: PurePosixPath(entry['output']).relative_to('review').as_posix()
              for entry in manifest['media']}
    blob = f'{REPOSITORY}/blob/{sha}/'

    def rewrite(match):
        attr, delimiter, encoded = match.groups()
        url = html.unescape(encoded)
        if url == '/':
            result = '../'
        elif url.startswith('#'):
            result = url
        else:
            relative = source_path(gallery, url)
            result = mapped.get(relative, blob + quote(relative, safe='/'))
            fragment = urlsplit(url).fragment
            if fragment:
                result += '#' + quote(fragment, safe='-_.')
        return f'{attr}={delimiter}{html.escape(result, quote=True)}{delimiter}'

    page = re.sub(r'\b(src|href|poster)=([\"\'])(.*?)\2', rewrite, source)
    page = page.replace('Local production · exterior v1', 'Published for assessment · exterior v1')
    page = page.replace('Implemented exterior proposal · artistic review pending.',
                        'Published for assessment · pending artistic acceptance.')
    page = page.replace('Open local exhibit', 'Open published exhibit')
    page = page.replace('Browser capture of this local build.',
                        f'Browser capture of exterior checkpoint {manifest["evidenceCheckpoint"][:7]}.')
    page = page.replace('Exact local runtime SHA-256:', 'Exact exterior model SHA-256:')
    page = page.replace('All MurderBird creative material is all rights reserved under NOTICE.md. '
                        'Local review only; this is distinct from the deployed website.',
                        'All MurderBird creative material is all rights reserved under '
                        f'<a href="{blob}NOTICE.md">NOTICE.md</a>. '
                        'Publication makes this checkpoint available for independent assessment; '
                        'it does not establish artistic acceptance.')
    revision_note = (
        '<p class="note">Exact publication build revision: '
        f'<a href="{REPOSITORY}/commit/{sha}"><code style="overflow-wrap:anywhere">{sha}</code></a>.'
        ' The comparison stills and motion recording preserve exterior checkpoint '
        f'<a href="{REPOSITORY}/commit/{manifest["evidenceCheckpoint"]}">'
        f'{manifest["evidenceCheckpoint"][:7]}</a>. '
        'The published application may include later integration changes; '
        'the model SHA below identifies the geometry reviewed here. '
        'Historical validation receipts are linked from the repository and retain their original scope.</p>'
    )
    page = page.replace('<nav>', revision_note + '<nav>', 1)
    require(manifest['model']['sha256'] in page, 'Gallery does not identify the pinned model')
    require('Published for assessment' in page and 'pending artistic acceptance' in page,
            'Missing assessment/acceptance status')
    require('This package does not yet meet the full artistic acceptance criteria.' in page,
            'Missing known artistic limitation')
    require(not re.search(r'127\.0\.0\.1|localhost|\[::1\]|file://|/Users/|/Volumes/', page),
            'Machine-local reference in generated gallery')
    require('Local production' not in page and 'Local review only' not in page,
            'Stale publication label')
    return page.encode('utf-8')


def check_output(dist, manifest, expected_page, sha):
    output = dist / 'review'
    expected = {'review/index.html'} | {entry['output'] for entry in manifest['media']}
    actual = {path.relative_to(dist).as_posix() for path in output.rglob('*') if path.is_file()}
    require(actual == expected,
            f'Review payload differs: extra={sorted(actual - expected)}, missing={sorted(expected - actual)}')
    require((output / 'index.html').read_bytes() == expected_page,
            'Generated gallery does not match pinned inputs and revision')
    for entry in manifest['media']:
        path = dist / entry['output']
        require(not path.is_symlink(), f'Symlink in review output: {entry["output"]}')
        data = path.read_bytes()
        require(not data.startswith(POINTER), f'LFS pointer in output: {entry["output"]}')
        require(len(data) == entry['bytes'] and hashlib.sha256(data).hexdigest() == entry['sha256'],
                f'Output hash/size mismatch: {entry["output"]}')
    references = References(expected_page.decode())
    for tag, attr, url in references.links:
        if url.startswith('#'):
            require(url[1:] in references.ids, f'Unresolved review anchor: {url}')
        elif url.startswith('https://'):
            require(url.startswith(f'{REPOSITORY}/blob/{sha}/') or
                    url in {f'{REPOSITORY}/commit/{sha}',
                            f'{REPOSITORY}/commit/{manifest["evidenceCheckpoint"]}'},
                    f'Unexpected or mutable external reference: {url}')
            require(attr == 'href', f'External runtime media: {url}')
        elif url == '../':
            require((dist / 'index.html').is_file(), 'Built exhibit index is missing')
        else:
            require(not urlsplit(url).scheme and not urlsplit(url).netloc, f'Unexpected URL: {url}')
            path = (output / unquote(urlsplit(url).path)).resolve()
            require(path.is_relative_to(output.resolve()) and path.is_file(),
                    f'Unresolved local review reference: {url}')
            require(path.relative_to(dist.resolve()).as_posix() in expected,
                    f'Unlisted local review reference: {url}')
    return {
        'status': 'PASS', 'buildRevision': sha, 'modelSha256': manifest['model']['sha256'],
        'gallerySha256': hashlib.sha256(expected_page).hexdigest(),
        'mediaFiles': len(manifest['media']), 'imageElements': len(references.media) - 1,
        'outputFiles': len(expected),
        'mediaBytes': sum(entry['bytes'] for entry in manifest['media']),
        'checks': ['pinned input hashes and media signatures', 'exact media allowlist',
                   'immutable repository links', 'local links and anchors',
                   'assessment and pending-acceptance labels', 'no loopback references or LFS pointers'],
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Validate the existing release derivative')
    parser.add_argument('--dist', default='dist', help='Build directory (default: dist)')
    args = parser.parse_args()
    dist = (ROOT / args.dist).resolve()
    require(dist.is_relative_to(ROOT) and dist != ROOT, 'Build directory must be within this checkout')
    require((dist / 'index.html').is_file(), 'Run the Vite build before preparing the review release')
    manifest, gallery, source = load_inputs()
    sha = revision()
    page = render(manifest, gallery, source, sha)
    if not args.check:
        expected = {'review/index.html'} | {entry['output'] for entry in manifest['media']}
        existing = {path.relative_to(dist).as_posix() for path in (dist / 'review').rglob('*') if path.is_file()}
        require(existing <= expected, 'Unexpected files in review output; rebuild Vite before release')
        (dist / 'review/media').mkdir(parents=True, exist_ok=True)
        for entry in manifest['media']:
            shutil.copyfile(local_file(entry['source']), dist / entry['output'])
        (dist / 'review/index.html').write_bytes(page)
    receipt = check_output(dist, manifest, page, sha)
    audit = ROOT / '.local/publication/review-release-validation.json'
    require(subprocess.run(['git', 'check-ignore', '--quiet', str(audit)], cwd=ROOT).returncode == 0,
            'Local receipt directory must be Git-ignored')
    audit.parent.mkdir(parents=True, exist_ok=True)
    audit.write_text(json.dumps(receipt, indent=2) + '\n')
    print(json.dumps(receipt, indent=2))


if __name__ == '__main__':
    main()
