from PIL import Image,ImageOps,ImageDraw
from pathlib import Path
import json,hashlib,datetime
R=Path('/Users/okh/.codex/worktrees/cg-architect-cycle01/murderbird-uncaged');O=R/'assets/audit/cg-supervised-head17';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
source=R/'assets/img/library/murderbird-locked-sept22-composite-owner-reissued-2026-10-03.jpg';jul=R/'assets/audit/cg-supervised01/cranial-projection-diagnosis15/cg-diagnosis15-july-source.png';lockedhead=O/'profile-source-before06-head17-pbr.png'
records={}
for v in ['source-full-bird','head-profile','head-grazing']:
 paths=[source if v=='source-full-bird' else jul,O/('before06-pbr-'+v+'.png'),O/'attempt02'/('after-pbr-'+v+'.png'),Path('/tmp/cg-ablation17-'+v+'.png')]
 labels=['LOCKED SEPT22 / FULL BIRD' if v=='source-full-bird' else 'PINNED JULY / HEAD ONLY','ACTUAL IMMUTABLE06','ACTUAL FROZEN HEAD17','HYPOTHETICAL OMIT ONE CREST']
 canv=Image.new('RGB',(2560,708),(25,25,25));d=ImageDraw.Draw(canv)
 for i,(p,l) in enumerate(zip(paths,labels)):
  im=Image.open(p).convert('RGB');im=ImageOps.contain(im,(632,632));canv.paste(im,(i*640+(640-im.width)//2,38+(632-im.height)//2));d.text((i*640+10,14),l,fill='white');records[str(p)]=sha(p)
 d.text((10,684),'06/17/omission: identical frozen cameras, lights, 4-sample denoised Cycles PBR. Source camera unknown. Unsaved selection test only.',fill='white');p=Path('/tmp/cg-ablation17-contact-'+v+'.png');canv.save(p)
# Locked-head supplementary source readback, drawn from actual frozen source comparison crop only.
p=Path('/tmp/cg-ablation17-source-head-contact.png');im=Image.open(lockedhead);im.crop((5,36,635,582)).save(p);records[str(lockedhead)]=sha(lockedhead)
Path('/tmp/cg-ablation17-contact-provenance.json').write_text(json.dumps({'inputs':records,'operations':'labeled resizes of actual pixels only; locked source crop extracted from frozen exact source comparison; no painting/generation','julyscope':'head only; body excluded'},indent=2))
r=json.loads(Path('/tmp/cg-ablation17-native.json').read_text())
r.update({'decision':'retainfull17','selection_verdict':'reject posterior-crest-only omission for integration; retain full17 only with existing provisional limits','hypothesis':'Omitting only CGH17 posterior swept crest restores06 taper/layered rear silhouette without losing17 warm hood or opening a coverage hole, yielding whole-character source gain over17.','hypothesis_result':'FALSIFIED as a whole-character source-gain claim in these three views. Profile cap reduction is real, but whole/grazing retain highest curled far brow while exposing a squared dark backing plate and stepped rear roof edge. Warm hood survives; no new through-hole established in sampled views. No all-angle coverage clearance claimed.','visual_findings':[{'view':'head-profile','tier':'INFERRED','finding':'The broad dark posterior cap disappears and retained06 trailing side layers read more cleanly. Exposed warm brow end remains blunt rather than the source thin pointed trailing sheet; local relief is insufficient evidence of full-character gain.'},{'view':'source-full-bird','tier':'INFERRED','finding':'Removal slightly reduces the rear roof bulk, but does not bring the whole character perceptibly closer to locked canon: the broad smooth gold hood and raised curled brow tips dominate. A small squared dark plate now interrupts the rear top edge.'},{'view':'head-grazing','tier':'INFERRED','finding':'The dark cap is replaced by a squared upright exposed plate plus a stepped dark roof strip behind the warm panel. This reads as unresolved backing/helmet construction, not source-coherent tapered feather layers.'},{'view':'all3','tier':'CONFIRMED-BOUNDED','finding':'Warm hood/brow courses remain visible, all retained object payloads/materials/FILE images unchanged in-memory; visibility changes exactly the named single crest. Three actual renders only; no native save or export.'}],
 'rear_coverage':'No clear new through-hole visible in these3 views. Squared exposed plate and stepped roof gap/edge weaken continuity. Rear/far/eight-angle clearance not tested; no all-angle coverage claim.',
 'numeric_note':'World maximum falls only0.0079809427m; whole/grazing projected highest remains far brow course0. Profile projected-highest now near brow course0. Counts/height reductions do not establish likeness.',
 'method_limits':['No full09 Equilibrium disruptor/owner/three-era/browser acceptance','No fresh camera/source reconstruction; source camera/depth unknown','Sampled optic first hits only; not continuous clearance','Projected-highest uses eligible upper evaluated vertices without visibility rays','No far/front/rear/eight-angle renders in this bounded single-hypothesis test','4-sample denoised native recipe; image judgment shares frozen17 lighting'],
 'checks_run':[{'check':'91 frozen manifest files and7source-hash entries before/after','status':'PASS'},{'check':'all in-memory17 MESH/EMPTY payloads,material graphs,packed FILE image metadata/bytes','status':'PASS','details':'digest unchanged across single visibility edit; historical06 preservation inherited from frozen17 review and disk custody'},{'check':'exactly one visibility edit; no native save/export/source edit','status':'PASS'},{'check':'actual3 PBR renders same frozen17 camera/light/settings','status':'PASS'},{'check':'913samples/eye first-hit comparison vs unmodified17','status':'PASS-BOUNDED','details':'0 losses in all3 views; far eye uninformative0/0/3 except grazing3'},{'check':'whole-character source gain versus17','status':'FAIL','details':'Profile relief not sustained as source-coherent whole/grazing crown construction'}],
 'checks_not_run':['Native or GLB save/export','UV geometry generation','New variants/wire renders','Full09 Equilibrium review','Full8angles/3era/browser','CI/deployment/npm build','Owner acceptance'],
 'next_action':'Keep full17 provisional warm-hood trial in full09 with posterior-crest correction still open. Do not implement the single-object omission based on this test.',
 'contacts':['/tmp/cg-ablation17-contact-source-full-bird.png','/tmp/cg-ablation17-contact-head-profile.png','/tmp/cg-ablation17-contact-head-grazing.png','/tmp/cg-ablation17-source-head-contact.png'],
 'created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()})
r['proofs']=[{'path':str(p),'sha256':sha(p)} for p in Path('/tmp').glob('cg-ablation17*') if p.is_file() and p.name!='cg-ablation17.json'];Path('/tmp/cg-ablation17.json').write_text(json.dumps(r,indent=2));print(r['decision'],r['hypothesis_result'])
