export const eras = {
  maker: {
    label: 'The Maker',
    number: 'I',
    period: 'Ancient construction',
    summary: 'Hand-worked bronze, irregular hammer marks, and peened pins shape a formidable terrestrial body. The original mechanism remains unresolved; the incomplete hillside fragments never became parts of the machine.',
    storyHref: 'https://overkillhill.com/writings/murderbird/#the-maker',
    firstPart: 'beak',
  },
  mechanic: {
    label: 'The Mechanic',
    number: 'II',
    period: 'Recovery and repair',
    summary: 'The 1853 discovery is followed by the 1873 repair shop: iron braces, brass bearings, and movement that borrows external power. The Bird stays floor-supported; this era adds no Builder processing lattice.',
    storyHref: 'https://overkillhill.com/writings/murderbird/#the-mechanic',
    firstPart: 'shoulder',
  },
  builder: {
    label: 'The Builder',
    number: 'III',
    period: 'Finite power / adaptive processing',
    summary: 'The 2025 additions separate carried energy from processing that learns. Stored energy is finite, the mind is a different system, and the inherited shoulder still sets a limit.',
    storyHref: 'https://overkillhill.com/writings/murderbird/#the-builder',
    firstPart: 'heart',
  },
};

export const specimens = [
  {
    id: 'beak',
    number: '01',
    name: 'Hooked beak',
    era: 'MAKER / ACTION',
    title: 'A shape from the commission',
    origin: 'The Maker drew a hooked bill for an unfamiliar body; the fragments never supplied a complete head.',
    repair: 'Hand-worked bronze retains varied edges and flattened pins. No later beak repair is established here.',
    constraint: 'A story design, not a certified fossil reconstruction or a proven weapon.',
    passage: '“The Maker drew a hooked bill above the unfamiliar body and folded ornamental wings against its sides.”',
    storyHref: 'https://overkillhill.com/writings/murderbird/#the-maker',
    observation: 'The preview gives the bill a deliberate, brief jaw snap on a visitor poke.',
    sound: 'metal',
  },
  {
    id: 'shoulder',
    number: '02',
    name: 'Left shoulder',
    era: 'MAKER → BUILDER / REPAIR HISTORY',
    title: 'Fitted twice. Travel limited.',
    origin: 'The Maker fitted the anatomical left plate backward, removed it, and fitted it again.',
    repair: 'The later Builder opens the shoulder; the movement model changes to respect the plate rather than replacing its history.',
    constraint: 'Only the anatomical left shoulder carries this double-fit history. Its wing folds within a limited stop.',
    passage: '“Beneath the left shoulder, the Maker had fitted one plate backward, removed it, and fitted it again.”',
    storyHref: 'https://overkillhill.com/writings/murderbird/#the-maker',
    observation: 'The procedural study keeps the refit asymmetric and the wing travel restrained.',
    sound: 'click',
  },
  {
    id: 'ankle',
    number: '03',
    name: 'Ankle and load',
    era: 'BUILDER / FIRST CHOICE',
    title: 'Read the load before failure',
    origin: 'A later ankle bracket flexes beneath the Bird’s carried weight.',
    repair: 'In the story, it shifts to the sound leg, lifts the other foot, and catches the loose bracket with its beak.',
    constraint: 'The preview shows a planted-foot weight transfer, not a biomechanical simulation or a literal replay of that event.',
    passage: '“It had felt the change, understood the likely consequence, and shifted its weight before the support failed.”',
    storyHref: 'https://overkillhill.com/writings/murderbird/#first-choice',
    observation: 'Both feet remain planted while the torso transfers load; the scene is a motion sketch.',
    sound: 'click',
  },
  {
    id: 'heart',
    number: '04',
    name: 'Heart / energy',
    era: 'BUILDER / FINITE POWER',
    title: 'Carry power. Measure its distance.',
    origin: 'Ceramic cells supply steady output; capacitors store short surges for lifting, bracing, or driving the beak.',
    repair: 'This replaces borrowed external power with an onboard reserve that must be replenished.',
    constraint: 'The reserve is finite. The Heart supplies current; it is not the learning system.',
    passage: '“When stored energy fell, the bird would have to return. Its freedom would have a distance it could measure.”',
    storyHref: 'https://overkillhill.com/writings/murderbird/#the-heart',
    observation: 'Open the Builder inspection to separate the chest energy cells from the cranial processing lattice.',
    sound: 'pulse',
  },
  {
    id: 'mind',
    number: '05',
    name: 'Mind / learning',
    era: 'BUILDER / PROCESSING',
    title: 'Change the model, not the scar',
    origin: 'A compact processing lattice behind the eyes lets the fictional Bird change its response with experience.',
    repair: 'The Builder adapts the movement model to the old shoulder stop rather than altering the plate.',
    constraint: 'This is the story’s modern learning system, not evidence that the unresolved ancient mechanism was proven intelligent.',
    passage: '“The model changed instead of the metal, and the bird folded the wing within its own limits.”',
    storyHref: 'https://overkillhill.com/writings/murderbird/#the-mind',
    observation: 'The inspection exposes a separate, non-emissive head lattice—not a chest-mounted brain.',
    sound: 'chirp',
  },
];