export const vocalScore = {
  title: 'Iron Verdict — vocal performance edition v2',
  tempo: '104 BPM',
  meter: '4/4',
  key: 'D minor',
  bars: '56 bars',
  range: 'D3–F4 sounding range',
  count: '233 words · 279 syllables · 102.12 seconds of sounding vocal time',
  opening: 'The instrumental begins at bar 1. First vocal: bar 5 at 0:09.23.',
  ending: 'Final vocal release: bar 54, beat 4 at 2:04.04. The band finishes on bar 55 at 2:04.62.',
  delivery: 'Read straight through; both choruses are written out with no repeats or improvised extensions. Keep verses grounded and intelligible, open the chorus vowels, and bring the bridge close and deliberate. Roughness is optional. Breathe in written rests, not inside hyphenated words or the tied final hold.',
  status: 'These are the complete written lyrics and performance instructions. Neither instrumental recording contains vocals. The pitch guide and rehearsal mix are synthetic rehearsal materials, not a singer recording.',
  sections: [
    {
      heading: 'A · Ignition · bar 1',
      direction: 'Instrumental. Count four full bars.',
      lines: [],
    },
    {
      heading: 'B · The Bird · bar 5',
      direction: 'Low and deliberate; sing on pitch.',
      lines: ['No crown.', 'No cage.', 'Just weight.', 'Just truth.'],
    },
    {
      heading: 'C · What the Water Kept · bar 9',
      direction: 'Tight rhythmic delivery; do not rush.',
      lines: [
        'Seven winters shaped this skin,',
        'Hammer marks are written in.',
        'Wings no king could teach to rise,',
        'Heavy feet and watchful eyes.',
        'Water darkened every seam,',
        'Names went quiet in the green.',
        'They could weigh me, name their price,',
        'Not the will behind these eyes.',
      ],
    },
    {
      heading: 'D · The Rebuild · bar 17',
      direction: 'Build intensity; keep the words clear.',
      lines: [
        'Iron braced the broken frame,',
        'Brass and borrowed power came.',
        'Every step a wound-up spring,',
        'No one there to choose a thing.',
        'Now a heartbeat runs with me.',
        'Now the choice belongs to me.',
        'Leave the old scar where it stays.',
        'I can learn another way.',
      ],
    },
    {
      heading: 'E · Under Load · bar 25',
      direction: 'Open and firm; sustain the final vowels.',
      lines: [
        'Put your promise under load.',
        "Don't look away.",
        'Let the hidden fracture show',
        'Before we fall.',
        'I will stand beside the hands',
        'That build it strong.',
        "I will find what doesn't hold.",
        'We carry on.',
      ],
    },
    {
      heading: 'F · Judgment · bar 33',
      direction: 'Pull close; feel the half-time drums.',
      lines: [
        'Some scars stay.',
        'Some seams give way.',
        'Leave the hammer marks.',
        "They don't make me weak.",
        'Before the order',
        "Leaves your mouth, I've seen",
        'Where the brace gives way.',
        'I shift before I fall.',
      ],
    },
    {
      heading: 'G · Iron Verdict · bar 41',
      direction: 'Full voice. Same melody, greater conviction.',
      lines: [
        'Put your promise under load.',
        "Don't look away.",
        'Let the hidden fracture show',
        'Before we fall.',
        'I will stand beside the hands',
        'That build it strong.',
        "I will find what doesn't hold.",
        'We carry on.',
      ],
    },
    {
      heading: 'H · The Unfinished File · bar 49',
      direction: 'Direct and rhythmic; return toward the low register.',
      lines: [
        "Close the file. I'll bring you back.",
        'One more fault beneath the patch.',
        'Leave no weakness dressed as done.',
        'We stay here till it can run.',
      ],
    },
    {
      heading: 'I · Final Word · bar 53',
      direction: 'Hold the vowel; release the final consonant at the notated release.',
      lines: ["Find what doesn't hold."],
    },
    {
      heading: 'J · Final Hit · bar 55',
      direction: 'Vocal tacet. Let the band finish.',
      lines: [],
    },
  ],
};