import bpy, json, importlib.util, hashlib
from pathlib import Path
import argparse,sys
p=argparse.ArgumentParser();p.add_argument('--input-root',required=True);a=p.parse_args(sys.argv[sys.argv.index('--')+1:]);root=Path(__file__).resolve().parents[3];inp=Path(a.input_root);out=root/'assets/audit/cg-supervised-body12/attempt02'
spec=importlib.util.spec_from_file_location('b12',root/'scripts/cg-supervised-body12.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
bpy.ops.wm.open_mainfile(filepath=str(out/'murderbird-body12.blend'));frozen={o.name:m.digest(o) for o in bpy.context.scene.objects if o.get('cgSupervisedBody12')};guide={o.name:m.digest(o) for o in bpy.context.scene.objects if o.get('cgSupervisedBody11')}
bpy.ops.wm.open_mainfile(filepath=str(inp/'assets/models/cg-supervised01/attempt06/murderbird-supervised-builder.blend'));s=bpy.context.scene;original={o.name:m.digest(o) for o in s.objects if o.type in ('MESH','EMPTY')};materials=m.material_digest();packed=m.packed_image_digest()
r=m.apply(s,inp,'builder');after={o.name:m.digest(o) for o in s.objects if o.get('cgSupervisedBody12')};afterguide={o.name:m.digest(o) for o in s.objects if o.get('cgSupervisedBody11')};changed=[n for n,h in original.items() if m.digest(s.objects[n])!=h]
assert after==frozen,'Panel deterministic payload mismatch';assert afterguide==guide,'Guide deterministic payload mismatch';assert not changed;assert materials==m.material_digest();assert packed==m.packed_image_digest()
p=dict(finalNativeSHA256=hashlib.sha256((out/'murderbird-body12.blend').read_bytes()).hexdigest(),moduleSHA256=hashlib.sha256((root/'scripts/cg-supervised-body12.py').read_bytes()).hexdigest(),source='receiving06',originalMeshesAndAnchors=len(original),changedOriginalPayloads=changed,materialGraphsUnchanged=materials==m.material_digest(),packedMapsUnchanged=packed==m.packed_image_digest(),newPanelPayloadsExactlyMatchFinalNative=after==frozen,newGuidePayloadExactlyMatchesRetainedGuide=afterguide==guide,hiddenOriginalCount=len(r['retainedHidden']),hiddenGuide=all(o.hide_render and o.hide_get() for o in s.objects if o.get('cgSupervisedBody11')),newPanelCount=r['newPanels'],nativeSaved=False,method='Reload receiving06, invoke standalone apply, compare all panel+guide payloads with final02; no save')
(out/'standalone-api-check.json').write_text(json.dumps(p,indent=2)+'\n');print(json.dumps(p,indent=2))
