import bpy,json
from pathlib import Path
from mathutils import Matrix,Vector
from bpy_extras.object_utils import world_to_camera_view
OUT=Path(__file__).resolve().parent
bpy.ops.wm.open_mainfile(filepath=str(OUT/'attempt02/formed-head12.blend'));scene=bpy.context.scene;frame=scene.objects['CG2b head frame'].matrix_world
R=json.loads((OUT/'attempt02/receipt.json').read_text());rows={}
for name in ['after-clay-source-full-bird','after-clay-head-profile','after-clay-head-grazing']:
 c=R['cameras'][name];scene.camera.matrix_world=Matrix(c['matrix']);scene.camera.data.ortho_scale=c['scale'];scene.camera.data.shift_x,scene.camera.data.shift_y=c['shift'];scene.render.resolution_x,scene.render.resolution_y=c['resolution'];bpy.context.view_layer.update()
 def proj(q):
  p=world_to_camera_view(scene,scene.camera,frame@q);return [p.x*c['resolution'][0],(1-p.y)*c['resolution'][1]]
 b=proj(Vector((0,0,0)));cols=[proj(Vector(v)) for v in [(1,0,0),(0,1,0),(0,0,1)]];rows[name]={'A_pixel_per_head_local_m':[[cols[j][i]-b[i] for j in range(3)] for i in range(2)],'b_pixels':b,'form':'pixels=A*head_local_xyz+b','camera':c}
controls={'posterior_crest':{'source_coordinate_label':[635,72,0],'head_local_m':[0,.1886,.1592],'cage_rings':'ring3 (8 controls), central top control3*8; evaluated named landmark snaps only within posterior crest mesh'},'near_brow':{'source_coordinate_label':[780,135,-.141],'head_local_m':[-.141,.0146,.0836],'cage_control':'near strip station3 (6 controls)'},'far_brow':{'source_coordinate_label':[780,144,.141],'head_local_m':[.141,.0146,.0728],'cage_control':'far strip station3 (6 controls)'},'foredeck_root':{'source_coordinate_label':[862,174,-.084],'head_local_m':[-.084,-.0838,.0368],'cage_control':'foredeck station1 (5 controls)'}}
r={'status':'NO simultaneous numerical solve ran. All controls manually proposed, then evaluated/measured at simultaneous fixed cameras. Two attempts stop; this does not isolate pose as sole blocker.','affine_projection_rows':rows,'control_locations':controls,'subsequent_fit_proposal':'Stack whole A35 x/y and profile A0 x/y into4x3 matrix for each homologous named physical control. Solve regularized weighted least squares against source-derived approximate target intervals registered by unchanged optic E and measured seat D. July perspective is head identity and uncertainty, not exact ortho coordinates. Fixed Catmull-Clark evaluated vertices are linear weighted combinations of cage controls for fixed topology; apply envelope inequalities to ALL evaluated head vertices, not a crest maximum over new meshes.','constraints_proposal':['Whole crown physical landmark posterior roughly0.9–1.5D and height1.1–1.5D; root0.6–1.0D anterior and within0.25D optic height, all inferred from source pixels.','Keep near/far brow separate and bounded in local depth/width; far brow may not become projected highest point or cross near aperture silhouette. Whole and grazing full evaluated head silhouette bound must preserve posterior crest dominance.','Use proposed width regularization and neighbor smoothness, then dense actual curved-lens baseline first-hit exclusion from ALL review cameras. Ray visibility and joins are nonlinear constraints and require evaluated/pixel readback after solving.','When fixed-camera targets/width/silhouette constraints conflict, report infeasibility and residuals; do not silently rotate pose or attribute failure solely to pose.'],'exact_source_camera':'UNKNOWN; camera04 inferred matched comparison only','completion':'HEAD12_PROJECTION_ROWS_COMPLETE'}
(OUT/'projection-feasibility.json').write_text(json.dumps(r,indent=2));print('HEAD12_PROJECTION_ROWS_COMPLETE',flush=True)
